# -*- coding: utf-8 -*-
"""Versión en español de las 3 páginas de Science. Traduce nodos de texto, strings del widget,
aria-labels y metadatos de las páginas EN ya generadas. Sin guiones largos."""
import re, json, os

META = {
 "/science": ("La ciencia detrás de Kinedu: cómo llegamos aquí | Kinedu",
              "Vimos crecer a 3.5 millones de niños. Lo que aprendimos es la base de Kinedu: de una lista de hitos a una evaluación que muestra lo que está emergiendo.",
              "Kinedu se construyó sobre cómo crecieron de verdad 3.5 millones de bebés | Kinedu"),
 "/science-what-we-know": ("Cinco cosas que hemos aprendido sobre cómo se desarrollan los bebés | Kinedu",
              "Lo que los datos de 3.5 millones de niños muestran sobre los primeros años: todo crece junto, las habilidades van en orden, el rango es amplio y ninguna gráfica predice a tu hijo.",
              "Cinco cosas que hemos aprendido sobre cómo se desarrollan los bebés | Kinedu"),
 "/science-what-you-can-do": ("Cuatro formas de apoyar el desarrollo de tu hijo | Kinedu",
              "Juego, relaciones, estrés y predictibilidad: las cuatro cosas a las que la evidencia sigue apuntando, y qué puede hacer con ellas un papá o una mamá.",
              "Cuatro formas de apoyar el desarrollo de tu hijo | Kinedu"),
}

H1 = {
 'How we built a clearer picture of <span class="gradient-shift">your baby’s development.</span>': 'Cómo construimos una imagen más clara <span class="gradient-shift">del desarrollo de tu bebé.</span>',
 'Five things we’ve learned about <span class="gradient-shift">how babies develop.</span>': 'Cinco cosas que hemos aprendido sobre <span class="gradient-shift">cómo se desarrollan los bebés.</span>',
 'Four ways to support your child’s <span class="gradient-shift">development.</span>': 'Cuatro formas de apoyar el <span class="gradient-shift">desarrollo</span> de tu hijo.',
}

T = {
'What data from 3.5 million children show about the early years.': 'Lo que los datos de 3.5 millones de niños muestran sobre los primeros años.',
'Your child’s pace': 'El ritmo de tu hijo',
'can change.': 'puede cambiar.',
'The chart below looks at a different question: how much an earlier assessment tells us about a child’s skill level later on.': 'La gráfica de abajo responde a una pregunta distinta: cuánto nos dice una evaluación temprana sobre el nivel de habilidades de un niño más adelante.',
'Explore the Kinedu app': 'Explora la app de Kinedu',
'Average share of caregiver “yes” answers across milestones in the babbling and first words skill groups, by age.': 'Promedio de respuestas “sí” de los cuidadores en los hitos de los grupos de balbuceo y primeras palabras, por edad.',
'Average share of caregiver “yes” answers across milestones in the walking skill group, by age.': 'Promedio de respuestas “sí” de los cuidadores en los hitos del grupo de caminar, por edad.',
'Age ranges shown for walking and self-care skill groups. See the chart caption for how the ranges are defined.': 'Rangos de edad de los grupos de caminar y de autocuidado. La leyenda de la gráfica explica cómo se definen los rangos.',
'Each bar spans the ages at which 25% and 75% of children in the Kinedu record were reported with the milestones in that skill group.': 'Cada barra va de la edad en que el 25% de los niños del registro de Kinedu fueron reportados con los hitos de ese grupo a la edad en que lo fue el 75%.',
# ---------- común ----------
"The science behind Kinedu · Part 1 of 3": "La ciencia detrás de Kinedu · Parte 1 de 3",
"The science behind Kinedu · Part 2 of 3": "La ciencia detrás de Kinedu · Parte 2 de 3",
"The science behind Kinedu · Part 3 of 3": "La ciencia detrás de Kinedu · Parte 3 de 3",
"About five minutes. Free, no app needed.": "Unos cinco minutos. Gratis y sin descargar nada.",
"Take the free assessment": "Haz la evaluación gratis",
"A checklist of milestones by age.": "Una lista de hitos por edad.",
"You can answer at home, based on what you see every day. Here’s a sample question from the assessment for 12&#8209;month&#8209;olds:": "Puedes contestar en casa, con lo que ves todos los días. Esta es una pregunta de ejemplo de la evaluación para bebés de 12 meses:",
"We consider each answer alongside your baby’s age and other skills.": "Consideramos cada respuesta junto con la edad de tu bebé y sus otras habilidades.",
"How we interpret your answers": "Cómo interpretamos tus respuestas",
"Answer simple questions about what your baby does.": "Contesta preguntas sencillas sobre lo que hace tu bebé.",
"That’s it.": "Eso es todo.",
"Built with insights from 3.5 million children, so you can see the skills your baby is building and what may come next.": "Construida con lo que aprendimos de 3.5 millones de niños, para que veas las habilidades que tu bebé está construyendo y lo que puede venir después.",
"Why we built it": "Por qué lo construimos",
"How skills develop": "Cómo se desarrollan las habilidades",
"How you can support them": "Cómo puedes apoyarlas",
"When your baby lifts their head, they can see more of the world and find new ways to respond to you. It’s one example of how movement, learning, communication, and relationships connect.": "Cuando tu bebé levanta la cabeza, ve más del mundo y encuentra nuevas formas de responderte. Es un ejemplo de cómo se conectan el movimiento, el aprendizaje, la comunicación y las relaciones.",
"Sees more of the room": "Ve más del cuarto",
"Can turn toward your voice": "Puede voltear hacia tu voz",
"Has more face-to-face moments with you": "Tiene más momentos cara a cara contigo",
"Early on, the four areas grow closely together.": "Al principio, las cuatro áreas crecen muy unidas.",
"As children get older, each area begins to follow its own path, while still influencing the others.": "Conforme los niños crecen, cada área empieza a seguir su propio camino, sin dejar de influir en las demás.",
"What your child is doing today doesn’t tell us how quickly the next skill will come. Where they are today and their pace of development are different things.": "Lo que tu hijo hace hoy no nos dice qué tan rápido llegará la siguiente habilidad. Dónde está hoy y su ritmo de desarrollo son cosas distintas.",
"An assessment is a snapshot, not a prediction.": "Una evaluación es una foto del momento, no una predicción.",
"Reads each answer alongside your baby’s age and other skills.": "Lee cada respuesta junto con la edad de tu bebé y sus otras habilidades.",
"Looks for what’s just beginning, not only what’s already mastered.": "Busca lo que apenas empieza, no solo lo que ya domina.",
"Expected ages checked against 3.5 million children.": "Edades esperadas verificadas con 3.5 millones de niños.",
"There’s no single right way to play.": "No hay una sola forma correcta de jugar.",
"Short videos with simple activities you can try together.": "Videos cortos con actividades sencillas para hacer juntos.",
"Want to go deeper?": "¿Quieres ir más a fondo?",
"Live classes": "Clases en vivo",
"Positive Education masterclass": "Masterclass de Educación Positiva",
"Sleep Habits masterclass": "Masterclass de Hábitos de Sueño",
"Supporting your child doesn’t have to mean adding more to your day. Four everyday forces, and all of them are already in your hands: Connect, Guide, Buffer, Repeat.": "Apoyar a tu hijo no tiene que significar sumarle cosas a tu día. Cuatro fuerzas cotidianas, y las cuatro ya están en tus manos: Conectar, Guiar, Proteger, Repetir.",
"The four forces": "Las cuatro fuerzas",
"Connect. Guide. Buffer.": "Conectar. Guiar. Proteger.",
"Repeat.": "Repetir.",
"The milestones in Part 2 are what you can see. What holds them together is invisible: how you play, how you relate, how you handle stress, and the routines you keep. None of it shows up on a chart. All of it is yours.": "Los hitos de la parte 2 son lo que puedes ver. Lo que los sostiene es invisible: cómo juegas, cómo te relacionas, cómo manejas el estrés y las rutinas que mantienes. Nada de eso aparece en una gráfica. Todo eso es tuyo.",
"Connect": "Conectar",
"Guide": "Guiar",
"Buffer": "Proteger",
"Repeat": "Repetir",
"Routines": "Rutinas",
"How you play together, and the kinds of play.": "Cómo juegan juntos, y los tipos de juego.",
"Push, protect, repair, model, and talk.": "Empujar, proteger, reparar, modelar y hablar.",
"The kinds of stress, and why most of it isn’t toxic.": "Los tipos de estrés, y por qué la mayoría no es tóxico.",
"The routines that give your child’s day its shape.": "Las rutinas que le dan forma al día de tu hijo.",
"Connect · Play": "Conectar · Juego",
"Guide · Relationships": "Guiar · Relaciones",
"Buffer · Stress": "Proteger · Estrés",
"Repeat · Routines": "Repetir · Rutinas",
"Your baby makes a sound. You respond. They respond again. That exchange is play, and it starts in the first weeks, long before anyone would call it playing. You don’t need special toys: your face, your voice, and your attention are the material.": "Tu bebé hace un sonido. Tú respondes. Vuelve a responder. Ese intercambio es juego, y empieza en las primeras semanas, mucho antes de que alguien lo llame jugar. No necesitas juguetes especiales: tu cara, tu voz y tu atención son el material.",
"As your child grows, play gets richer and your role shifts: sometimes they lead, sometimes you set things up, sometimes you show them how.": "Conforme tu hijo crece, el juego se enriquece y tu papel cambia: a veces él lleva la iniciativa, a veces tú preparas el terreno, a veces le enseñas cómo.",
"Your child chooses what to do and how. This is where creativity and curiosity get practice.": "Tu hijo elige qué hacer y cómo. Aquí es donde practica la creatividad y la curiosidad.",
"You offer a prompt or a challenge and follow their lead. Good for specific skills like shapes, counting, and switching between tasks.": "Tú propones una idea o un reto y sigues su iniciativa. Funciona bien para habilidades concretas como formas, contar y cambiar de una tarea a otra.",
"Taking turns, following rules, trying again.": "Esperar turnos, seguir reglas, volver a intentar.",
"You show, they try. Useful for specific skills like tying shoes, but on its own it’s not play.": "Tú enseñas, ellos intentan. Útil para habilidades concretas como amarrarse los zapatos, pero por sí solo no es juego.",
"Ask what you want to nurture right now, with this child.": "Pregúntate qué quieres cultivar en este momento, con este hijo.",
"What makes it play: it’s fun, it means something to them, they’re doing rather than watching, they can try again, and you’re in it together.": "Lo que lo convierte en juego: es divertido, significa algo para ellos, están haciendo y no mirando, pueden volver a intentar, y están en eso juntos.",
"Your relationship is built from": "Tu relación se construye con",
"more than play.": "más que juego.",
"Play builds the bond, but the bond is made of much more: how you push, protect, repair, model, and talk. Warmth and high expectations aren’t opposites. They work best together.": "El juego construye el vínculo, pero el vínculo está hecho de mucho más: cómo empujas, proteges, reparas, modelas y hablas. La calidez y las expectativas altas no son opuestas. Funcionan mejor juntas.",
"Push.": "Empujar.",
"Nudge them past their comfort zone. Hold the limit, and hold them while they’re upset about it. Struggling a little is how character gets built.": "Anímalo a salir de su zona de confort. Mantén el límite, y abrázalo mientras se enoja por él. Batallar un poco es como se forja el carácter.",
"Protect.": "Proteger.",
"You are your child’s first way of handling big feelings. First you soothe them, then you name the feeling for them, and little by little they learn to do it themselves.": "Tú eres la primera forma que tiene tu hijo de manejar emociones grandes. Primero lo calmas, luego le pones nombre a lo que siente, y poco a poco aprende a hacerlo solo.",
"Repair.": "Reparar.",
"You’ll snap sometimes. Come back, own it without excuses, and reconnect. Your child doesn’t need a perfect parent. They need one who returns.": "A veces vas a explotar. Regresa, reconócelo sin excusas y vuelve a conectar. Tu hijo no necesita un papá perfecto. Necesita uno que regrese.",
"Model.": "Modelar.",
"They learn to handle frustration by watching you handle yours. A breath instead of a yell teaches more than any lesson.": "Aprende a manejar la frustración viendo cómo manejas la tuya. Una respiración en vez de un grito enseña más que cualquier lección.",
"Talk.": "Hablar.",
"Praise effort, character, and the person when you mean it. Say no when you mean it. Real beats scripted.": "Elogia el esfuerzo, el carácter y a la persona cuando lo sientas. Di que no cuando lo sientas. Lo auténtico le gana al guion.",
"Holding a limit isn’t the opposite of warmth.": "Mantener un límite no es lo opuesto a la calidez.",
"It’s warmth in action.": "Es calidez en acción.",
"Being upset is not the same as being harmed. Most of the stress your child feels is the normal kind, and you are what keeps it that way.": "Estar molesto no es lo mismo que estar dañado. La mayor parte del estrés que siente tu hijo es del tipo normal, y tú eres quien hace que siga siéndolo.",
"A hard puzzle, the first day at school, hearing no. Brief, normal, and back to calm with you nearby. Your child needs this kind.": "Un rompecabezas difícil, el primer día de escuela, escuchar un no. Breve, normal, y de vuelta a la calma contigo cerca. Tu hijo necesita este tipo.",
"A medical procedure, a move, a scare. Real stress, but a caring adult absorbs enough of it for your child to recover.": "Un procedimiento médico, una mudanza, un susto. Estrés real, pero un adulto que lo cuida absorbe lo suficiente para que tu hijo se recupere.",
"Prolonged, severe, and with no adult to buffer it. This is what damages development, and it isn’t one bad day or one bad week.": "Prolongado, severo y sin un adulto que lo amortigüe. Esto es lo que daña el desarrollo, y no es un mal día ni una mala semana.",
"Saying no, holding a limit, letting them feel frustrated: that’s positive stress, and it’s necessary.": "Decir que no, mantener un límite, dejar que se frustre: eso es estrés positivo, y es necesario.",
"The buffer isn’t the absence of the stressor.": "Lo que protege a tu hijo no es la ausencia del estrés.",
"It’s you being there.": "Es que tú estés ahí.",
"Routines tell your child": "Las rutinas le dicen a tu hijo",
"what comes next.": "qué viene después.",
"When Stanford’s Phil Fisher was asked for the one thing he would recommend to every parent, his answer was a single word: “Predictability.” When your child knows what comes next, their mind is free to learn instead of bracing for what’s coming.": "Cuando le preguntaron a Phil Fisher, de Stanford, la única cosa que le recomendaría a todos los papás, su respuesta fue una sola palabra: “Predictability” (predictibilidad). Cuando tu hijo sabe qué viene después, su mente queda libre para aprender en vez de prepararse para lo que viene.",
"Reading": "Lectura",
"The one routine where all four forces meet: it’s play, it’s closeness, it’s calm, and it’s the same ritual every night. Point, ask, let them turn the page.": "La única rutina donde se juntan las cuatro fuerzas: es juego, es cercanía, es calma, y es el mismo ritual cada noche. Señala, pregunta, deja que pase la página.",
"Meals": "Comidas",
"Together, at roughly the same time. Fed is best; the rest is about the habit of sharing the table.": "Juntos, más o menos a la misma hora. Que coma es lo primero; lo demás es el hábito de compartir la mesa.",
"Bath": "Baño",
"A daily anchor that doubles as playtime, and the natural preamble to bed.": "Un ancla diaria que también es hora de juego, y el preámbulo natural de la cama.",
"Sleep": "Sueño",
"Naps help lock in what they learned that morning. At night, keep the last hour calm and the sequence the same: teeth, pajamas, book, song, lights off.": "Las siestas ayudan a fijar lo que aprendió en la mañana. En la noche, mantén la última hora tranquila y la secuencia igual: dientes, pijama, cuento, canción, luces apagadas.",
"Connect. Guide. Buffer. Repeat.": "Conectar. Guiar. Proteger. Repetir.",
"The four forces aren’t a menu. They’re one thing: you, showing up, day after day.": "Las cuatro fuerzas no son un menú. Son una sola cosa: tú, presente, día tras día.",
"More than a milestone checklist": "Más que una lista de hitos",
"From checking milestones to seeing how": "De marcar hitos a ver cómo",
"skills grow together.": "las habilidades crecen juntas.",
"Then · 2013": "Antes · 2013",
"Now · today": "Ahora · hoy",
"A connected view of how your baby’s skills are taking shape.": "Una mirada conectada de cómo van tomando forma las habilidades de tu bebé.",
"Shaped by data from millions of children.": "Moldeado con datos de millones de niños.",
"Here’s how the assessment grew from its first version to the one families use today.": "Así creció la evaluación, desde su primera versión hasta la que usan las familias hoy.",
"We tested the first version with 2,135 caregivers to make sure the questions were clear and useful. Stanford researcher Michael C. Frank also helped us review milestones from birth to 24 months.": "Probamos la primera versión con 2,135 cuidadores para asegurarnos de que las preguntas fueran claras y útiles. El investigador de Stanford Michael C. Frank también nos ayudó a revisar los hitos del nacimiento a los 24 meses.",
"Stanford researchers studied Kinedu data from 21,861 children. They found that developmental skills are closely connected early in life and become more distinct as children grow.": "Investigadores de Stanford estudiaron datos de Kinedu de 21,861 niños. Encontraron que las habilidades del desarrollo están muy conectadas al principio de la vida y se vuelven más distintas conforme los niños crecen.",
"Read the Stanford research →": "Lee la investigación de Stanford →",
"We looked again, this time at 281 million caregiver observations from 3.5 million children. The same pattern held: skills are more connected early on and become more distinct with age.": "Volvimos a mirar, esta vez con 281 millones de observaciones de cuidadores de 3.5 millones de niños. El patrón se repitió: las habilidades están más conectadas al principio y se vuelven más distintas con la edad.",
"That research helped us understand not just when skills appear,": "Esa investigación nos ayudó a entender no solo cuándo aparecen las habilidades,",
"but how they build on one another.": "sino cómo se construyen unas sobre otras.",
"One milestone doesn’t tell": "Un hito no cuenta",
"the whole story.": "toda la historia.",
"Instead of asking only whether a skill has appeared, we look at how it’s taking shape over time. Walking, for example, begins long before those first independent steps:": "En vez de preguntar solo si una habilidad ya apareció, miramos cómo va tomando forma con el tiempo. Caminar, por ejemplo, empieza mucho antes de esos primeros pasos sin ayuda:",
"It often starts here": "Suele empezar aquí",
"Next": "Después",
"Then": "Luego",
"Eventually": "Y con el tiempo",
"See where each skill is taking shape,": "Ve en qué punto va tomando forma cada habilidad,",
"not just whether it has happened yet.": "no solo si ya pasó o no.",
"In about five minutes, tell us what you’re seeing day to day. We’ll help you understand what’s taking shape and what may come next.": "En unos cinco minutos, cuéntanos lo que ves día a día. Te ayudamos a entender qué va tomando forma y qué puede venir después.",
"Next: How skills develop →": "Siguiente: Cómo se desarrollan las habilidades →",
"Next: How you can support them →": "Siguiente: Cómo puedes apoyarlas →",
"← Why we built it": "← Por qué lo construimos",
"← How skills develop": "← Cómo se desarrollan las habilidades",
"Stanford researchers.": "investigadores de Stanford.",
"Walks while holding onto the sofa": "Camina agarrado del sillón",
"Takes steps while holding your hand": "Da pasos tomado de tu mano",
"Takes steps independently": "Da pasos sin ayuda",
"Every skill in Kinedu is shown along a path like this one:": "Cada habilidad en Kinedu se muestra a lo largo de un camino como este:",
"Usually develops at a later age.": "Suele desarrollarse a una edad mayor.",
"Expected around this age; still developing.": "Se espera alrededor de esta edad; aún en desarrollo.",
"Showing at the expected age.": "Se muestra a la edad esperada.",
"Showing consistently.": "Se muestra de forma consistente.",
"and what may come next.": "y de lo que puede venir después.",
"Can your baby stand up from a squat without help?": "¿Tu bebé se pone de pie desde cuclillas sin ayuda?",
"In our data, caregivers reported this skill in 49.5% of 12-month-olds.": "En nuestros datos, los cuidadores reportaron esta habilidad en el 49.5% de los bebés de 12 meses.",
"Does your baby push a button or flip a switch to make something happen?": "¿Tu bebé aprieta un botón o mueve un interruptor para que algo pase?",
"Cognitive questions look at how your baby explores and solves problems.": "Las preguntas cognitivas miran cómo explora tu bebé y cómo resuelve problemas.",
"Does your baby wave bye-bye when someone waves first?": "¿Tu bebé dice adiós con la mano cuando alguien lo hace primero?",
"Social-emotional questions look at how your baby connects with people.": "Las preguntas socioemocionales miran cómo se conecta tu bebé con las personas.",
"That’s it.": "Eso es todo.",
"32 questions like these, in about 5 minutes, adapted to your child’s age.": "32 preguntas como estas, en unos 5 minutos, adaptadas a la edad de tu hijo.",
"This is an example, not an individual child’s result.": "Es un ejemplo, no el resultado de un niño en particular.",
"We compare your answers with patterns in caregiver reports across ages. Together, they help us understand which skills your baby is developing. You don’t need special training to answer.": "Comparamos tus respuestas con los patrones de reportes de cuidadores en distintas edades. En conjunto, nos ayudan a entender qué habilidades está desarrollando tu bebé. No necesitas ninguna preparación especial para contestar.",
"“Lifts head while on tummy”: share of caregivers reporting it, by age, across the Kinedu population · Kinedu record, 2020–2023 · a population pattern, not an individual baby’s path": "“Levanta la cabeza boca abajo”: porcentaje de cuidadores que lo reportan, por edad, en la población de Kinedu · Datos de Kinedu, 2020–2023 · un patrón poblacional, no el camino de un bebé en particular",
"From holding their head up to jumping on one foot.": "De sostener la cabeza a saltar en un pie.",
"Exploring, solving problems, and playing pretend.": "Explorar, resolver problemas y jugar a imaginar.",
"From babbling to words and sentences.": "Del balbuceo a las palabras y las frases.",
"Connecting, expressing feelings, and playing with others.": "Conectar, expresar emociones y jugar con otros.",
"What the results mean": "Qué significan los resultados",
"What the assessment can tell you,": "Lo que la evaluación puede decirte,",
"and what it can’t.": "y lo que no.",
"Show which skills your baby is developing": "Mostrar qué habilidades está desarrollando tu bebé",
"and what usually comes next.": "y lo que suele venir después.",
"Help you prepare questions": "Ayudarte a preparar preguntas",
"for your child’s healthcare professional.": "para el profesional de salud de tu hijo.",
"Put your observations in context": "Poner tus observaciones en contexto",
"using patterns from other children’s development.": "con patrones del desarrollo de otros niños.",
"Provide a diagnosis.": "Dar un diagnóstico.",
"The assessment supports conversations with a qualified healthcare professional.": "La evaluación apoya la conversación con un profesional de salud calificado.",
"Evaluate your parenting.": "Evaluar tu forma de criar.",
"These data describe children’s skills, not the care they receive.": "Estos datos describen las habilidades de los niños, no el cuidado que reciben.",
"Represent every family.": "Representar a todas las familias.",
"The findings come from families who chose to use Kinedu.": "Los hallazgos vienen de familias que decidieron usar Kinedu.",
"See which skills your baby": "Descubre qué habilidades",
"is building.": "está construyendo tu bebé.",
"The science, in three parts": "La ciencia, en tres partes",
"Try it free": "Pruébalo gratis",
"In the Kinedu app": "En la app de Kinedu",

# ---------- página 1 ----------
"By 9 months": "A los 9 meses",
"Sits without support": "Se sienta sin apoyo",
"Passes a toy from hand to hand": "Pasa un juguete de una mano a la otra",
"Says “mama” or “dada”": "Dice “mamá” o “papá”",
"Pulls up to stand": "Se pone de pie agarrándose",
"yes / no · by age · one line per milestone": "sí / no · por edad · un hito por línea",
"An old-style milestone checklist by age": "Una lista de hitos por edad, como las de antes",
"How we got there": "Cómo llegamos hasta aquí",
"Built by Kinedu. Studied by": "Creado por Kinedu. Estudiado por",
"caregivers": "papás y mamás",
"children": "niños",
"The rebuild": "La nueva evaluación",
"then": "luego",
"Upcoming": "En camino",
"Reinforce": "Reforzar",
"On track": "Adquiridas",
"Mastered": "Sobresaliente",
"How the assessment works": "Así funciona la evaluación",
"0 mo": "0 m", "3 mo": "3 m", "5 mo": "5 m",
"What the assessment covers": "Qué cubre la evaluación",
"414 milestones.": "414 hitos.",
"46 skills.": "46 habilidades.",
"Four areas.": "Cuatro áreas.",
"Physical": "Física",
"Cognitive": "Cognitiva",
"Language": "Lenguaje",
"Social-emotional": "Socioemocional",
"What it can do": "Lo que sí puede",
"What it cannot do": "Lo que no puede",
"Research report": "Reporte de investigación",
"PDF · full methods and figures": "PDF · métodos y gráficas completas",
"Parent’s guide": "Guía para papás",
"PDF · the findings in plain language": "PDF · los hallazgos en lenguaje sencillo",
"Coupling and Differentiation in Early Development · July 2026 · Kinedu supports developmental surveillance. It is not a diagnosis.": "Coupling and Differentiation in Early Development · Julio 2026 · Kinedu apoya la vigilancia del desarrollo. No es un diagnóstico.",
"Your turn": "Te toca a ti",
"Developmental surveillance. Not a diagnosis.": "Vigilancia del desarrollo. No es un diagnóstico.",
# widget
"Standing up": "Ponerse de pie", "Imitation": "Imitación", "Cause and effect": "Causa y efecto",
"Not yet": "Todavía no", "Yes": "Sí",
"Try it with your child →": "Pruébala con tu hijo →",
"See the questions again ↺": "Ver las preguntas otra vez ↺",
# aria
"Share of babies who lift their head while on tummy, by age: 17% at birth, 48% at 3 months, 93% at 5 months": "Porcentaje de bebés que levantan la cabeza boca abajo, por edad: 17% al nacer, 48% a los 3 meses, 93% a los 5 meses",
"How tightly the four areas move together, by age: 0.49 at 2 months falling to 0.27 at 14 months and staying there": "Qué tan unidas avanzan las cuatro áreas, por edad: 0.49 a los 2 meses, baja a 0.27 a los 14 meses y ahí se estabiliza",
"Skills stacked in order: lifts their head at about 3 months, sits at 7, stands at 12, walks at 13": "Habilidades en orden: levanta la cabeza cerca de los 3 meses, se sienta a los 7, se pone de pie a los 12, camina a los 13",
"Windows: exploring objects 1 to 5 months, first steps 8 to 13 months, first words 14 to 25 months": "Ventanas: explorar objetos de 1 a 5 meses, primeros pasos de 8 a 13, primeras palabras de 14 a 25",

# ---------- página 2 ----------
"Why five": "Por qué cinco",
"One · Together": "Uno · Todo junto",
"Five patterns that help": "Cinco patrones que ayudan a",
"explain development.": "explicar el desarrollo.",
"Together, these ideas help make sense of how skills connect, when they appear, and why children develop at different paces.": "Juntas, estas ideas ayudan a entender cómo se conectan las habilidades, cuándo aparecen y por qué cada niño se desarrolla a su propio ritmo.",
"Early skills": "Las primeras habilidades",
"develop together.": "se desarrollan juntas.",
"…and that one skill opens new possibilities:": "…y esa sola habilidad abre nuevas posibilidades:",
"closely linked": "muy ligadas",
"more distinct, still linked": "más distintas, todavía ligadas",
"how linked the four areas are (0 to 1)": "qué tan ligadas están las cuatro áreas (0 a 1)",
"The connection between the four areas falls by almost half during the first year, then remains more stable through the ages shown · Kinedu record, 2020–2023 · children observed at consecutive ages between 2 and 35 months · technical name: within-child coupling": "La conexión entre las cuatro áreas cae casi a la mitad durante el primer año y luego se mantiene más estable en las edades mostradas · Datos de Kinedu, 2020–2023 · niños observados en edades consecutivas entre los 2 y los 35 meses · nombre técnico: acoplamiento intra-niño",
"Skills build on": "Las habilidades se construyen sobre",
"earlier skills.": "habilidades anteriores.",
"Babbling helps lay the groundwork for words. Pulling up to stand helps prepare the way for independent steps. These sequences help us understand what a child may be working toward.": "El balbuceo ayuda a sentar las bases de las palabras. Ponerse de pie agarrándose ayuda a preparar el camino para los primeros pasos solo. Estas secuencias nos ayudan a entender hacia qué puede estar avanzando un niño.",
"Expected age: when three in four children have the skill · The order is typical, the timing varies · Kinedu record": "Edad esperada: cuando tres de cada cuatro niños ya tienen la habilidad · El orden es típico, los tiempos varían · Datos de Kinedu",
"From babbling to first words.": "Del balbuceo a las primeras palabras.",
"As children develop early speech, the assessment shifts its focus from babbling to words.": "Conforme los niños desarrollan el habla temprana, la evaluación cambia su foco del balbuceo a las palabras.",
"Average share of “yes” answers across the milestones in each skill group, by age · Kinedu record, 2020–2023 · shaded band ±1 SD": "Promedio de respuestas “sí” entre los hitos de cada grupo de habilidades, por edad · Datos de Kinedu, 2020–2023 · banda sombreada ±1 DE",
"From first steps to more confident movement.": "De los primeros pasos a un movimiento más seguro.",
"This skill group includes several milestones, from taking first steps to more advanced movement.": "Este grupo de habilidades incluye varios hitos, desde dar los primeros pasos hasta movimientos más avanzados.",
"Average share of “yes” answers across the milestones in this skill group, by age · Kinedu record, 2020–2023": "Promedio de respuestas “sí” entre los hitos de este grupo de habilidades, por edad · Datos de Kinedu, 2020–2023",
"Children reach milestones across a wide": "Los niños alcanzan los hitos en un rango de edades",
"range of ages.": "muy amplio.",
"For some skills, children reach them within a few months of one another. For others, the range spans well over a year, and it tends to widen as children grow.": "En algunas habilidades, los niños las alcanzan con pocos meses de diferencia entre sí. En otras, el rango abarca bastante más de un año, y tiende a ampliarse conforme crecen.",
"a reference point, not a deadline.": "un punto de referencia, no una fecha límite.",
"A learning window": "Una ventana de aprendizaje no es",
"isn’t a countdown.": "una cuenta regresiva.",
"The chart shows when reports of these skills become more common in our data. These age ranges describe a pattern, not a deadline for an individual child.": "La gráfica muestra cuándo se vuelven más comunes en nuestros datos los reportes de estas habilidades. Estos rangos de edad describen un patrón, no una fecha límite para un niño en particular.",
"Each assessment captures a moment in your child’s development. Checking in again helps you see what has changed.": "Cada evaluación captura un momento del desarrollo de tu hijo. Volver a hacerla te ayuda a ver qué ha cambiado.",
"at age 2, it says little about where they stand": "a los 2 años, dice poco sobre dónde está",
"3 months later, it still says a lot about where they stand": "3 meses después, todavía dice mucho sobre dónde está",
"Checking in again:": "Volver a evaluar:",
"An assessment is a photograph: one taken at 3 months says little by age 2, one taken at 2 years still says a lot three months later, so check in again every few months": "Una evaluación es una fotografía: una tomada a los 3 meses dice poco a los 2 años, una tomada a los 2 años todavía dice mucho tres meses después, así que vuelve a evaluar cada pocos meses",
"In this analysis, current skill level explained about 1.5% of the variation in subsequent developmental pace.": "En este análisis, el nivel actual de habilidades explicó cerca del 1.5% de la variación en el ritmo de desarrollo posterior.",
"Lifts their head": "Levanta la cabeza",
"child age, months": "edad en meses",
"Two · In order": "Dos · En orden",
"≈ 3 mo": "≈ 3 m", "≈ 7 mo": "≈ 7 m", "≈ 12 mo": "≈ 12 m", "≈ 13 mo": "≈ 13 m",
"Sits": "Se sienta", "Stands": "Se pone de pie", "Walks": "Camina",
"Babbling →": "Balbuceo →",
"First words": "Primeras palabras",
"Three · Wide": "Tres · Amplio",
"Learning to walk": "Aprender a caminar",
"8–13 mo · a 5-month range": "8–13 m · un rango de 5 meses",
"Dressing and feeding themselves": "Vestirse y comer solo",
"17–39 mo · a 22-month range": "17–39 m · un rango de 22 meses",
"42 months": "42 meses",
"8–13 mo · 5 months wide": "8–13 m · 5 meses de rango",
"17–39 mo · 22 months wide": "17–39 m · 22 meses de rango",
"An expected age is": "Una edad esperada es",
"Four · Windows": "Cuatro · Ventanas",
"Exploring objects": "Explorar objetos",
"1–5 mo": "1–5 m", "8–13 mo": "8–13 m", "14–25 mo": "14–25 m",
"First steps": "Primeros pasos",
"Five · Unpredictable": "Cinco · Impredecible",

"Walking": "Caminar",
"your baby’s age, months": "edad de tu bebé, en meses",
"Assessment at 3 months": "Evaluación a los 3 meses",
"Assessment at 2 years": "Evaluación a los 2 años",
"a new picture every few months": "una foto nueva cada pocos meses",
# ---------- página 3 ----------
"One": "Uno", "Two": "Dos", "Three": "Tres", "Four": "Cuatro",
"Play": "Juego", "Relationships": "Relaciones", "Stress": "Estrés", "Predictability": "Predictibilidad",
"Play starts with the back-and-forth": "El juego empieza con el ida y vuelta",
"between you.": "entre ustedes.",
"smile or talk back": "sonríes o le hablas",
"responds": "responde",
"Daily activity ideas": "Ideas de actividades diarias",
"Your baby": "Tu bebé",
"coos": "balbucea",
"You": "Tú",
"…and so on, back and forth": "…y así, una y otra vez",
"They lead": "Tu bebé lidera",
"You guide": "Tú guías",
"Your baby leads": "Tu bebé guía",
"You set it up, they run it": "Tú preparas, tu bebé lleva",
"Rules, with room to play": "Reglas, pero con espacio",
"You lead": "Tú diriges",
"Free play": "Juego libre",
"Guided play": "Juego guiado",
"Games": "Juegos",
"Direct instruction": "Instrucción directa",
"Not all stress is": "No todo el estrés",
"the same.": "es igual.",
"Positive": "Positivo",
"Tolerable": "Tolerable",
"Toxic": "Tóxico",
"Find ideas for putting these principles into practice with your child.": "Encuentra ideas para poner estos principios en práctica con tu hijo.",
"Explore Kinedu": "Explora Kinedu",
"Keep it simple, familiar,": "Que sea sencilla, conocida",
"and flexible.": "y flexible.",
}

from l10n import localize
def to_es(html, path): return localize(html, path, 'es', META, H1, T)
