# -*- coding: utf-8 -*-
"""Versión en español de las 3 páginas de Science. Traduce nodos de texto, strings del widget,
aria-labels y metadatos de las páginas EN ya generadas. Sin guiones largos."""
import re, json, os

META = {
 "/science": ("La ciencia detrás de Kinedu: cómo llegamos aquí | Kinedu",
              "Vimos crecer a 3.5 millones de niños. Lo que aprendimos es la base de Kinedu: de una lista de hitos a una evaluación que muestra lo que está emergiendo.",
              "Kinedu se construyó sobre cómo crecieron de verdad 3.5 millones de bebés | Kinedu"),
 "/science-what-we-know": ("Cinco cosas que hemos aprendido sobre cómo se desarrollan los bebés | Kinedu",
              "Lo que los datos de 3.5 millones de niños muestran sobre los primeros años: todo crece junto, las habilidades van en orden, el rango es amplio y ninguna gráfica predice a tu hijo.",
              "Cinco cosas que hemos aprendido sobre cómo se desarrollan los bebés | Kinedu"),
 "/science-what-you-can-do": ("Cuatro formas de apoyar el desarrollo de tu hijo | Kinedu",
              "Juego, relaciones, estrés y predictibilidad: las cuatro cosas a las que la evidencia sigue apuntando, y qué puede hacer con ellas un papá o una mamá.",
              "Cuatro formas de apoyar el desarrollo de tu hijo | Kinedu"),
}

H1 = {
 'How we built Kinedu’s <span class="gradient-shift">developmental assessment.</span>': 'Cómo construimos la <span class="gradient-shift">evaluación del desarrollo</span> de Kinedu.',
 'Five things we’ve learned about <span class="gradient-shift">how babies develop.</span>': 'Cinco cosas que hemos aprendido sobre <span class="gradient-shift">cómo se desarrollan los bebés.</span>',
 'Four ways to support your child’s <span class="gradient-shift">development.</span>': 'Cuatro formas de apoyar el <span class="gradient-shift">desarrollo</span> de tu hijo.',
}

T = {
'What data from 3.5 million children show about the early years.': 'Lo que los datos de 3.5 millones de niños muestran sobre los primeros años.',
'Everyday ways to play, connect, help your child through stress, and build familiar routines.': 'Formas cotidianas de jugar, conectar, acompañar a tu hijo en el estrés y construir rutinas conocidas.',
'Your child’s pace': 'El ritmo de tu hijo',
'can change.': 'puede cambiar.',
'The chart below looks at a different question: how much an earlier assessment tells us about a child’s skill level later on.': 'La gráfica de abajo responde a una pregunta distinta: cuánto nos dice una evaluación temprana sobre el nivel de habilidades de un niño más adelante.',
'Explore the Kinedu app': 'Explora la app de Kinedu',
'Explore live classes': 'Explora las clases en vivo',
'Explore the Positive Education masterclass': 'Explora la masterclass de Educación Positiva',
'Explore the Sleep Habits masterclass': 'Explora la masterclass de Hábitos de Sueño',
'Get the Baby Tracker in the app': 'Usa el Baby Tracker en la app',
'Average share of caregiver “yes” answers across milestones in the babbling and first words skill groups, by age.': 'Promedio de respuestas “sí” de los cuidadores en los hitos de los grupos de balbuceo y primeras palabras, por edad.',
'Average share of caregiver “yes” answers across milestones in the walking skill group, by age.': 'Promedio de respuestas “sí” de los cuidadores en los hitos del grupo de caminar, por edad.',
'Age ranges shown for walking and self-care skill groups. See the chart caption for how the ranges are defined.': 'Rangos de edad de los grupos de caminar y de autocuidado. La leyenda de la gráfica explica cómo se definen los rangos.',
'Each bar spans the ages at which 25% and 75% of children in the Kinedu record were reported with the milestones in that skill group.': 'Cada barra va de la edad en que el 25% de los niños del registro de Kinedu fueron reportados con los hitos de ese grupo a la edad en que lo fue el 75%.',
# ---------- común ----------
"The science behind Kinedu · Part 1 of 3": "La ciencia detrás de Kinedu · Parte 1 de 3",
"The science behind Kinedu · Part 2 of 3": "La ciencia detrás de Kinedu · Parte 2 de 3",
"The science behind Kinedu · Part 3 of 3": "La ciencia detrás de Kinedu · Parte 3 de 3",
"About five minutes. Free, no app needed.": "Unos cinco minutos. Gratis y sin descargar nada.",
"Take the free assessment": "Haz la evaluación gratis",
"Informed by data from 3.5 million children. Designed to help you understand your baby’s developing skills.": "Con datos de 3.5 millones de niños. Diseñada para ayudarte a entender las habilidades que tu bebé está desarrollando.",
"Then": "Antes",
"Now": "Ahora",
"A checklist of milestones by age.": "Una lista de hitos por edad.",
"A connected picture of the skills your baby is developing.": "Una imagen conectada de las habilidades que tu bebé está desarrollando.",
"Tell us what your baby": "Cuéntanos qué hace",
"does.": "tu bebé.",
"Answer simple questions based on everyday moments.": "Responde preguntas sencillas sobre momentos del día a día.",
"We consider each answer alongside your baby’s age and other skills.": "Consideramos cada respuesta junto con la edad de tu bebé y sus otras habilidades.",
"How we interpret your answers": "Cómo interpretamos tus respuestas",
"From milestones to a clearer picture": "De los hitos a una imagen más clara",
"How Kinedu’s assessment": "Cómo ha evolucionado",
"has evolved.": "la evaluación de Kinedu.",
"Stanford researchers.": "investigadores de Stanford.",
"Informed by millions of children.": "Nutrido por millones de niños.",
"From the first assessment to research at a much larger scale.": "De la primera evaluación a la investigación a una escala mucho mayor.",
"We tested the first assessment with 2,135 caregivers. Stanford researcher Michael C. Frank reviewed the milestones from birth to 24 months.": "Probamos la primera evaluación con 2,135 cuidadores. El investigador de Stanford Michael C. Frank revisó los hitos del nacimiento a los 24 meses.",
"Stenhaug, Ram, and Frank analyzed Kinedu data from 21,861 children. The four areas of development were closely linked early in life and became more distinct with age. Published as the preprint “The Structure of Developmental Variation in Early Childhood”.": "Stenhaug, Ram y Frank analizaron datos de Kinedu de 21,861 niños. Las cuatro áreas del desarrollo estaban muy ligadas al principio de la vida y se volvían más distintas con la edad. Publicado en el preprint “The Structure of Developmental Variation in Early Childhood”.",
"We repeated the analysis with 281 million caregiver observations from 3.5 million children. The same pattern held. Our expected ages matched the data, with a median difference of zero months.": "Repetimos el análisis con 281 millones de observaciones de cuidadores, de 3.5 millones de niños. El mismo patrón se mantuvo. Nuestras edades esperadas coincidieron con los datos, con una diferencia mediana de cero meses.",
"That research helped us map": "Esa investigación nos ayudó a trazar",
"how skills develop and connect.": "cómo se desarrollan y se conectan las habilidades.",
"We wanted to understand how a skill is taking shape.": "Queríamos entender cómo va tomando forma una habilidad.",
"Walking begins well before those first independent steps:": "Caminar empieza mucho antes de esos primeros pasos sin ayuda:",
"developing skills.": "las habilidades en desarrollo.",
"Walks while holding onto the sofa": "Camina agarrado del sillón",
"Takes steps while holding your hand": "Da pasos tomado de tu mano",
"Takes steps independently": "Da pasos sin ayuda",
"Every skill in Kinedu is shown along a path like this one:": "Cada habilidad en Kinedu se muestra a lo largo de un camino como este:",
"Usually develops at a later age.": "Suele desarrollarse a una edad mayor.",
"Expected around this age; still developing.": "Se espera alrededor de esta edad; aún en desarrollo.",
"Showing at the expected age.": "Se muestra a la edad esperada.",
"Showing consistently.": "Se muestra de forma consistente.",
"A clearer picture of the skills your baby is building": "Una imagen más clara de las habilidades que tu bebé está construyendo",
"and what may come next.": "y de lo que puede venir después.",
"Can your baby stand up from a squat without help?": "¿Tu bebé se pone de pie desde cuclillas sin ayuda?",
"In our data, caregivers reported this skill in 49.5% of 12-month-olds.": "En nuestros datos, los cuidadores reportaron esta habilidad en el 49.5% de los bebés de 12 meses.",
"Does your baby push a button or flip a switch to make something happen?": "¿Tu bebé aprieta un botón o mueve un interruptor para que algo pase?",
"Cognitive questions look at how your baby explores and solves problems.": "Las preguntas cognitivas miran cómo explora tu bebé y cómo resuelve problemas.",
"Does your baby wave bye-bye when someone waves first?": "¿Tu bebé dice adiós con la mano cuando alguien lo hace primero?",
"Social-emotional questions look at how your baby connects with people.": "Las preguntas socioemocionales miran cómo se conecta tu bebé con las personas.",
"That’s it.": "Eso es todo.",
"32 questions like these, in about 5 minutes, adapted to your child’s age.": "32 preguntas como estas, en unos 5 minutos, adaptadas a la edad de tu hijo.",
"This is an example, not an individual child’s result.": "Es un ejemplo, no el resultado de un niño en particular.",
"We compare your answers with patterns in caregiver reports across ages. Together, they help us understand which skills your baby is developing. You don’t need special training to answer.": "Comparamos tus respuestas con los patrones de reportes de cuidadores en distintas edades. En conjunto, nos ayudan a entender qué habilidades está desarrollando tu bebé. No necesitas ninguna preparación especial para contestar.",
"“Lifts head while on tummy”: share of caregivers reporting it, by age, across the Kinedu population · Kinedu record, 2020–2023 · a population pattern, not an individual baby’s path": "“Levanta la cabeza boca abajo”: porcentaje de cuidadores que lo reportan, por edad, en la población de Kinedu · Datos de Kinedu, 2020–2023 · un patrón poblacional, no el camino de un bebé en particular",
"From holding their head up to jumping on one foot.": "De sostener la cabeza a saltar en un pie.",
"How your child moves and uses their body.": "Cómo se mueve tu hijo y cómo usa su cuerpo.",
"Exploring, solving problems, and playing pretend.": "Explorar, resolver problemas y jugar a imaginar.",
"How your child learns about the world.": "Cómo aprende tu hijo sobre el mundo.",
"From babbling to words and sentences.": "Del balbuceo a las palabras y las frases.",
"How your child understands and communicates.": "Cómo entiende y se comunica tu hijo.",
"Connecting, expressing feelings, and playing with others.": "Conectar, expresar emociones y jugar con otros.",
"How your child relates to people and handles emotions.": "Cómo se relaciona tu hijo con las personas y cómo maneja sus emociones.",
"What the results mean": "Qué significan los resultados",
"What the assessment can tell you,": "Lo que la evaluación puede decirte,",
"and what it can’t.": "y lo que no.",
"Show which skills your baby is developing": "Mostrar qué habilidades está desarrollando tu bebé",
"and what usually comes next.": "y lo que suele venir después.",
"Help you prepare questions": "Ayudarte a preparar preguntas",
"for your child’s healthcare professional.": "para el profesional de salud de tu hijo.",
"Put your observations in context": "Poner tus observaciones en contexto",
"using patterns from other children’s development.": "con patrones del desarrollo de otros niños.",
"Provide a diagnosis.": "Dar un diagnóstico.",
"The assessment supports conversations with a qualified healthcare professional.": "La evaluación apoya la conversación con un profesional de salud calificado.",
"Evaluate your parenting.": "Evaluar tu forma de criar.",
"These data describe children’s skills, not the care they receive.": "Estos datos describen las habilidades de los niños, no el cuidado que reciben.",
"Represent every family.": "Representar a todas las familias.",
"The findings come from families who chose to use Kinedu.": "Los hallazgos vienen de familias que decidieron usar Kinedu.",
"See which skills your baby": "Descubre qué habilidades",
"is building.": "está construyendo tu bebé.",
"In about five minutes, answer questions about everyday behaviors and get a clearer picture of your baby’s developing skills.": "En unos cinco minutos, contesta preguntas sobre conductas de todos los días y obtén una imagen más clara de las habilidades que tu bebé está desarrollando.",
"The science, in three parts": "La ciencia, en tres partes",
"How Kinedu was built": "Cómo nació Kinedu",
"How babies grow": "Cómo crecen los bebés",
"What you can do as a parent": "Lo que puedes hacer como papá",
"Next: How babies grow →": "Siguiente: Cómo crecen los bebés →",
"Next: What you can do as a parent →": "Siguiente: Lo que puedes hacer como papá →",
"← How Kinedu was built": "← Cómo nació Kinedu",
"← How babies grow": "← Cómo crecen los bebés",
"Try it free": "Pruébalo gratis",
"Live classes and the Positive Education masterclass": "Clases en vivo y la masterclass de Educación Positiva",
"See live classes": "Ver clases en vivo",
"Ask an expert live": "Pregúntale a un experto en vivo",
"Baby Tracker and the Sleep Habits masterclass": "Baby Tracker y la masterclass de Hábitos de Sueño",
"In the Kinedu app": "En la app de Kinedu",
"References to Stanford, Harvard’s Center on the Developing Child and named researchers are for attribution only and do not imply endorsement of Kinedu. Nothing on this page is medical advice.": "Las menciones a Stanford, al Center on the Developing Child de Harvard y a los investigadores citados son solo de atribución y no implican ningún respaldo a Kinedu. Nada de lo que hay en esta página es consejo médico.",

# ---------- página 1 ----------
"By 9 months": "A los 9 meses",
"Sits without support": "Se sienta sin apoyo",
"Passes a toy from hand to hand": "Pasa un juguete de una mano a la otra",
"Says “mama” or “dada”": "Dice “mamá” o “papá”",
"Pulls up to stand": "Se pone de pie agarrándose",
"yes / no · by age · one line per milestone": "sí / no · por edad · un hito por línea",
"An old-style milestone checklist by age": "Una lista de hitos por edad, como las de antes",
"How we got there": "Cómo llegamos hasta aquí",
"Built by Kinedu. Studied by": "Creado por Kinedu. Estudiado por",
"caregivers": "papás y mamás",
"children": "niños",
"The rebuild": "La nueva evaluación",
"We rebuilt the assessment around": "Rediseñamos la evaluación alrededor de",
"a different question.": "una pregunta distinta.",
"months earlier": "meses antes",
"then": "luego",
"and finally": "y por fin",
"Upcoming": "En camino",
"Reinforce": "Reforzar",
"On track": "Adquiridas",
"Mastered": "Sobresaliente",
"How the assessment works": "Así funciona la evaluación",
"0 mo": "0 m", "3 mo": "3 m", "5 mo": "5 m",
"What the assessment covers": "Qué cubre la evaluación",
"414 milestones. 46 skills.": "414 hitos. 46 habilidades.",
"Four areas.": "Cuatro áreas.",
"Physical": "Física",
"Cognitive": "Cognitiva",
"Language": "Lenguaje",
"Social-emotional": "Socioemocional",
"What it can do": "Lo que sí puede",
"What it cannot do": "Lo que no puede",
"Research report": "Reporte de investigación",
"PDF · full methods and figures": "PDF · métodos y gráficas completas",
"Parent’s guide": "Guía para papás",
"PDF · the findings in plain language": "PDF · los hallazgos en lenguaje sencillo",
"Coupling and Differentiation in Early Development · July 2026 · Kinedu supports developmental surveillance. It is not a diagnosis.": "Coupling and Differentiation in Early Development · Julio 2026 · Kinedu apoya la vigilancia del desarrollo. No es un diagnóstico.",
"Your turn": "Te toca a ti",
"Developmental surveillance. Not a diagnosis.": "Vigilancia del desarrollo. No es un diagnóstico.",
# widget
"Standing up": "Ponerse de pie", "Imitation": "Imitación", "Cause and effect": "Causa y efecto",
"Not yet": "Todavía no", "Yes": "Sí",
"Try it with your child →": "Pruébala con tu hijo →",
"See the questions again ↺": "Ver las preguntas otra vez ↺",
# aria
"Share of babies who lift their head while on tummy, by age: 17% at birth, 48% at 3 months, 93% at 5 months": "Porcentaje de bebés que levantan la cabeza boca abajo, por edad: 17% al nacer, 48% a los 3 meses, 93% a los 5 meses",
"How tightly the four areas move together, by age: 0.49 at 2 months falling to 0.27 at 14 months and staying there": "Qué tan unidas avanzan las cuatro áreas, por edad: 0.49 a los 2 meses, baja a 0.27 a los 14 meses y ahí se estabiliza",
"Skills stacked in order: lifts their head at about 3 months, sits at 7, stands at 12, walks at 13": "Habilidades en orden: levanta la cabeza cerca de los 3 meses, se sienta a los 7, se pone de pie a los 12, camina a los 13",
"Windows: exploring objects 1 to 5 months, first steps 8 to 13 months, first words 14 to 25 months": "Ventanas: explorar objetos de 1 a 5 meses, primeros pasos de 8 a 13, primeras palabras de 14 a 25",

# ---------- página 2 ----------
"Why five": "Por qué cinco",
"One · Together": "Uno · Todo junto",
"Five patterns that help": "Cinco patrones que ayudan a",
"explain development.": "explicar el desarrollo.",
"Together, these ideas help make sense of how skills connect, when they appear, and why children develop at different paces.": "Juntas, estas ideas ayudan a entender cómo se conectan las habilidades, cuándo aparecen y por qué cada niño se desarrolla a su propio ritmo.",
"Early skills": "Las primeras habilidades",
"develop together.": "se desarrollan juntas.",
"Holding their head up gives your baby new ways to look around and interact. It’s one example of how movement, learning, communication, and relationships connect.": "Sostener la cabeza le da a tu bebé nuevas formas de mirar alrededor e interactuar. Es un ejemplo de cómo se conectan el movimiento, el aprendizaje, la comunicación y las relaciones.",
"…and that one skill opens new possibilities:": "…y esa sola habilidad abre nuevas posibilidades:",
"A new view of the room": "Una nueva vista del cuarto",
"More ways to respond to your voice": "Más formas de responder a tu voz",
"More opportunities for face-to-face interaction": "Más oportunidades de interactuar cara a cara",
"The four areas become more distinct as children grow.": "Las cuatro áreas se vuelven más distintas conforme los niños crecen.",
"This measure shows how closely progress across the four areas is linked. It falls by almost half during the first year, then remains more stable through the ages shown.": "Esta medida muestra qué tan ligado está el avance entre las cuatro áreas. Baja casi a la mitad durante el primer año y después se mantiene más estable en las edades que se muestran.",
"closely linked": "muy ligadas",
"more distinct, still linked": "más distintas, todavía ligadas",
"how linked the four areas are (0 to 1)": "qué tan ligadas están las cuatro áreas (0 a 1)",
"Kinedu record, 2020–2023 · children observed at consecutive ages between 2 and 35 months · technical name: within-child coupling": "Datos de Kinedu, 2020–2023 · niños observados en edades consecutivas entre los 2 y los 35 meses · nombre técnico: acoplamiento intra-niño",
"Skills build on": "Las habilidades se construyen sobre",
"earlier skills.": "habilidades anteriores.",
"Babbling helps lay the groundwork for words. Pulling up to stand helps prepare the way for independent steps. These sequences help us understand what a child may be working toward.": "El balbuceo ayuda a sentar las bases de las palabras. Ponerse de pie agarrándose ayuda a preparar el camino para los primeros pasos solo. Estas secuencias nos ayudan a entender hacia qué puede estar avanzando un niño.",
"Expected age: when three in four children have the skill · The order is typical, the timing varies · Kinedu record": "Edad esperada: cuando tres de cada cuatro niños ya tienen la habilidad · El orden es típico, los tiempos varían · Datos de Kinedu",
"From babbling to first words.": "Del balbuceo a las primeras palabras.",
"As children develop early speech, the assessment shifts its focus from babbling to words.": "Conforme los niños desarrollan el habla temprana, la evaluación cambia su foco del balbuceo a las palabras.",
"Average share of “yes” answers across the milestones in each skill group, by age · Kinedu record, 2020–2023 · shaded band ±1 SD": "Promedio de respuestas “sí” entre los hitos de cada grupo de habilidades, por edad · Datos de Kinedu, 2020–2023 · banda sombreada ±1 DE",
"From first steps to more confident movement.": "De los primeros pasos a un movimiento más seguro.",
"This skill group includes several milestones, from taking first steps to more advanced movement.": "Este grupo de habilidades incluye varios hitos, desde dar los primeros pasos hasta movimientos más avanzados.",
"Average share of “yes” answers across the milestones in this skill group, by age · Kinedu record, 2020–2023": "Promedio de respuestas “sí” entre los hitos de este grupo de habilidades, por edad · Datos de Kinedu, 2020–2023",
"Children reach milestones across a wide": "Los niños alcanzan los hitos en un rango de edades",
"range of ages.": "muy amplio.",
"For some skills, children reach them within a few months of one another. For others, the range spans well over a year, and it tends to widen as children grow.": "En algunas habilidades, los niños las alcanzan con pocos meses de diferencia entre sí. En otras, el rango abarca bastante más de un año, y tiende a ampliarse conforme crecen.",
"a reference point, not a deadline.": "un punto de referencia, no una fecha límite.",
"A learning window": "Una ventana de aprendizaje no es",
"isn’t a countdown.": "una cuenta regresiva.",
"The chart shows when reports of these skills become more common in our data. These age ranges describe a pattern, not a deadline for an individual child.": "La gráfica muestra cuándo se vuelven más comunes en nuestros datos los reportes de estas habilidades. Estos rangos de edad describen un patrón, no una fecha límite para un niño en particular.",
"A child’s current skill level tells us little about how quickly they’ll progress next. Where they are today and their pace of development are different things.": "El nivel actual de habilidades de un niño nos dice poco sobre qué tan rápido va a avanzar después. Dónde está hoy y su ritmo de desarrollo son cosas distintas.",
"Each assessment captures a moment in your child’s development. Checking in again helps you see what has changed.": "Cada evaluación captura un momento del desarrollo de tu hijo. Volver a hacerla te ayuda a ver qué ha cambiado.",
"at age 2, it says little about where they stand": "a los 2 años, dice poco sobre dónde está",
"3 months later, it still says a lot about where they stand": "3 meses después, todavía dice mucho sobre dónde está",
"Checking in again:": "Volver a evaluar:",
"An assessment is a photograph: one taken at 3 months says little by age 2, one taken at 2 years still says a lot three months later, so check in again every few months": "Una evaluación es una fotografía: una tomada a los 3 meses dice poco a los 2 años, una tomada a los 2 años todavía dice mucho tres meses después, así que vuelve a evaluar cada pocos meses",
"In this analysis, current skill level explained about 1.5% of the variation in subsequent developmental pace.": "En este análisis, el nivel actual de habilidades explicó cerca del 1.5% de la variación en el ritmo de desarrollo posterior.",
"Lifts their head": "Levanta la cabeza",
"child age, months": "edad en meses",
"Two · In order": "Dos · En orden",
"≈ 3 mo": "≈ 3 m", "≈ 7 mo": "≈ 7 m", "≈ 12 mo": "≈ 12 m", "≈ 13 mo": "≈ 13 m",
"Sits": "Se sienta", "Stands": "Se pone de pie", "Walks": "Camina",
"Babbling →": "Balbuceo →",
"First words": "Primeras palabras",
"Three · Wide": "Tres · Amplio",
"Learning to walk": "Aprender a caminar",
"8–13 mo · a 5-month range": "8–13 m · un rango de 5 meses",
"Dressing and feeding themselves": "Vestirse y comer solo",
"17–39 mo · a 22-month range": "17–39 m · un rango de 22 meses",
"42 months": "42 meses",
"8–13 mo · 5 months wide": "8–13 m · 5 meses de rango",
"17–39 mo · 22 months wide": "17–39 m · 22 meses de rango",
"An expected age is": "Una edad esperada es",
"Four · Windows": "Cuatro · Ventanas",
"Exploring objects": "Explorar objetos",
"1–5 mo": "1–5 m", "8–13 mo": "8–13 m", "14–25 mo": "14–25 m",
"First steps": "Primeros pasos",
"Five · Unpredictable": "Cinco · Impredecible",

"Walking": "Caminar",
"An assessment is a photograph, not a prophecy.": "Una evaluación es una fotografía, no una profecía.",
"your baby’s age, months": "edad de tu bebé, en meses",
"Assessment at 3 months": "Evaluación a los 3 meses",
"Assessment at 2 years": "Evaluación a los 2 años",
"a new picture every few months": "una foto nueva cada pocos meses",
# ---------- página 3 ----------
"Where this comes from": "De dónde viene esto",
"One": "Uno", "Two": "Dos", "Three": "Tres", "Four": "Cuatro",
"Play": "Juego", "Relationships": "Relaciones", "Stress": "Estrés", "Predictability": "Predictibilidad",
"Everyday moments give you": "Los momentos de todos los días te dan",
"ways to help.": "formas de ayudar.",
"Kinedu’s data help us understand how children’s skills develop. The ideas on this page come from broader research on parenting and child development. They focus on four parts of everyday life:": "Los datos de Kinedu nos ayudan a entender cómo se desarrollan las habilidades de los niños. Las ideas de esta página vienen de una investigación más amplia sobre crianza y desarrollo infantil. Se centran en cuatro partes de la vida diaria:",
"Follow their curiosity. Join the back-and-forth.": "Sigue su curiosidad. Súmate al ida y vuelta.",
"Warmth, connection, and clear limits.": "Cariño, conexión y límites claros.",
"Help them through difficult moments.": "Acompáñalo en los momentos difíciles.",
"Build routines they can recognize.": "Crea rutinas que pueda reconocer.",
"Play starts with the back-and-forth": "El juego empieza con el ida y vuelta",
"between you.": "entre ustedes.",
"Your baby makes a sound. You respond. They respond again. Researchers call these back-and-forth exchanges “serve and return.” Your face, voice, and attention are part of the interaction.": "Tu bebé hace un sonido. Tú respondes. Tu bebé responde otra vez. Los investigadores llaman a estos intercambios de ida y vuelta “servir y devolver”. Tu cara, tu voz y tu atención son parte de la interacción.",
"smile or talk back": "sonríes o le hablas",
"responds": "responde",
"As your child grows, your role in play changes. Sometimes they lead. Sometimes you offer a prompt, introduce a rule, or show them how something works.": "Conforme tu hijo crece, tu papel en el juego cambia. A veces él guía. A veces tú le propones algo, introduces una regla o le muestras cómo funciona algo.",
"Your child chooses what to explore and how to use it. There’s room to invent, experiment, and follow their curiosity.": "Tu hijo elige qué explorar y cómo usarlo. Hay espacio para inventar, experimentar y seguir su curiosidad.",
"You create an opportunity or offer a prompt, while your child leads the exploration. With colored cups, for example, you might invite them to sort or compare.": "Tú creas una oportunidad o le propones algo, y tu hijo guía la exploración. Con vasos de colores, por ejemplo, puedes invitarlo a ordenarlos o compararlos.",
"Simple games give children practice taking turns, following rules, and trying again.": "Los juegos sencillos le dan práctica en tomar turnos, seguir reglas y volver a intentar.",
"You show your child how to do a specific task, then give them a chance to try.": "Le muestras a tu hijo cómo hacer una tarea concreta y después le das la oportunidad de intentarlo.",
"Choose the approach that fits": "Elige el enfoque que va con",
"what your child is exploring.": "lo que tu hijo está explorando.",
"Daily activity ideas": "Ideas de actividades diarias",
"Short videos that show you how to try activities with your baby.": "Videos cortos que te muestran cómo hacer actividades con tu bebé.",
"Harvard’s Center on the Developing Child describes three types of stress response: positive, tolerable, and toxic. The intensity, duration, and support available to a child matter.": "El Center on the Developing Child de Harvard describe tres tipos de respuesta al estrés: positiva, tolerable y tóxica. Importan la intensidad, la duración y el apoyo con el que cuenta el niño.",
"A brief challenge, with support from a caring adult, followed by a return to calm.": "Un reto breve, con el apoyo de un adulto que lo cuida, seguido de un regreso a la calma.",
"A more serious difficulty. Supportive relationships help the child cope and recover.": "Una dificultad más seria. Las relaciones de apoyo ayudan al niño a enfrentarla y recuperarse.",
"Prolonged or excessive stress without adequate adult support. This can affect development and long-term health.": "Estrés prolongado o excesivo sin el apoyo adecuado de un adulto. Puede afectar el desarrollo y la salud a largo plazo.",
"One · Play": "Uno · Juego",
"Your baby": "Tu bebé",
"coos": "balbucea",
"You": "Tú",
"…and so on, back and forth": "…y así, una y otra vez",
"Your baby in charge": "Tu bebé manda",
"You in charge": "Tú diriges",
"Your baby leads": "Tu bebé guía",
"You set it up, they run it": "Tú preparas, tu bebé lleva",
"Rules, with room to play": "Reglas, pero con espacio",
"You lead": "Tú diriges",
"Free play": "Juego libre",
"Guided play": "Juego guiado",
"Games": "Juegos",
"Direct instruction": "Instrucción directa",
"Two · Relationships": "Dos · Relaciones",
"Warmth and clear limits": "El cariño y los límites claros",
"can go together.": "pueden ir juntos.",
"You can respond to your child’s feelings while keeping a clear limit. The goal is to offer support and expectations that fit their age.": "Puedes responder a lo que siente tu hijo y al mismo tiempo mantener un límite claro. La idea es ofrecerle apoyo y expectativas acordes a su edad.",
"You can say no with care.": "Puedes decir que no con cariño.",
"Your child can feel upset about a limit and still receive your comfort and support.": "Tu hijo puede sentirse molesto por un límite y aun así recibir tu consuelo y tu apoyo.",
"Keep the limit. Stay connected.": "Mantén el límite. Mantén la conexión.",
"Acknowledge the feeling and explain the boundary in simple words.": "Reconoce lo que siente y explícale el límite con palabras sencillas.",
"Help them find their calm.": "Ayúdalo a encontrar la calma.",
"Offer a calm voice and support while they learn to handle strong feelings.": "Ofrécele una voz tranquila y apoyo mientras aprende a manejar emociones intensas.",
"You won’t get every moment right. You can reconnect and try again.": "No vas a acertar en todos los momentos. Siempre puedes reconectar y volver a intentarlo.",
"Learn ways to set limits with care and respond to tantrums, with guidance from child psychologists.": "Aprende formas de poner límites con cariño y responder a los berrinches, con la guía de psicólogas infantiles.",
"Your support can help your child": "Tu apoyo puede ayudar a tu hijo",
"through difficult moments.": "a atravesar los momentos difíciles.",
"Bring your questions to a live class.": "Trae tus preguntas a una clase en vivo.",
"Three · Stress": "Tres · Estrés",
"Not all stress is": "No todo el estrés",
"the same.": "es igual.",
"Positive": "Positivo",
"Tolerable": "Tolerable",
"Toxic": "Tóxico",
"Connect. Guide. Protect. Repeat.": "Conecta. Guía. Protege. Repite.",
"Find ideas for putting these principles into practice with your child.": "Encuentra ideas para poner estos principios en práctica con tu hijo.",
"Explore Kinedu": "Explora Kinedu",
"Four · Predictability": "Cuatro · Predictibilidad",
"Familiar routines help your child know": "Las rutinas conocidas ayudan a tu hijo a saber",
"what comes next.": "qué sigue.",
"When our team asked Phil Fisher, of the Stanford Center on Early Childhood, what advice he would give parents, he emphasized predictability: familiar routines children can count on.": "Cuando nuestro equipo le preguntó a Phil Fisher, del Stanford Center on Early Childhood, qué consejo le daría a los papás, él insistió en la predictibilidad: rutinas conocidas con las que los niños pueden contar.",
"Familiar patterns around meals, play, and bedtime can make the day easier to recognize. A routine can be simple and still leave room to adapt.": "Patrones conocidos alrededor de las comidas, el juego y la hora de dormir hacen que el día sea más fácil de reconocer. Una rutina puede ser sencilla y aun así dejar espacio para adaptarse.",
"A familiar rhythm, day after day": "Un ritmo conocido, día tras día",
"Keep it simple, familiar,": "Que sea sencilla, conocida",
"and flexible.": "y flexible.",
"Keep track of feeds, naps, and diaper changes in one place. Explore bedtime routines in the Sleep Habits masterclass.": "Lleva el registro de tomas, siestas y cambios de pañal en un solo lugar. Explora rutinas para dormir en la masterclass de Hábitos de Sueño.",
"Wake up": "Despertar", "Meals": "Comidas", "Play": "Juego", "Nap": "Siesta", "Bath": "Baño", "Bedtime": "Dormir",
}

from l10n import localize
def to_es(html, path): return localize(html, path, 'es', META, H1, T)
