# -*- coding: utf-8 -*-
"""Versão em português (Brasil) das 3 páginas de Science. Mesmas chaves EN que es.py."""
from l10n import localize

META = {
 "/science": ("A ciência por trás do Kinedu: como chegamos até aqui | Kinedu",
              "Construímos o Kinedu vendo 3,5 milhões de crianças crescerem. O que aprendemos virou a base do app: de uma lista de marcos a uma avaliação que mostra o que está surgindo.",
              "O Kinedu foi construído sobre como 3,5 milhões de bebês realmente cresceram | Kinedu"),
 "/science-what-we-know": ("Cinco coisas que sabemos sobre como os bebês crescem | Kinedu",
              "O que 3,5 milhões de crianças nos ensinaram: tudo cresce junto, as habilidades vêm em ordem, o normal é amplo e nenhum gráfico prevê o seu filho.",
              "Cinco coisas que sabemos sobre como os bebês crescem | Kinedu"),
 "/science-what-you-can-do": ("E o que você pode fazer? Quatro coisas nas suas mãos | Kinedu",
              "Brincadeira, vínculo, estresse e previsibilidade: as quatro coisas para as quais a evidência sempre aponta, e o que um pai ou uma mãe pode fazer com elas.",
              "E o que você pode fazer? Quatro coisas nas suas mãos | Kinedu"),
}

H1 = {
 'Kinedu is built on how <span class="gradient-shift">3.5 million</span> babies actually grew.': 'O Kinedu foi construído sobre como <span class="gradient-shift">3,5 milhões</span> de bebês realmente cresceram.',
 'Five things we know about <span class="gradient-shift">how babies grow.</span>': 'Cinco coisas que sabemos sobre <span class="gradient-shift">como os bebês crescem.</span>',
 'So what can <span class="gradient-shift">you</span> do, as a parent?': 'E o que <span class="gradient-shift">você</span> pode fazer, como pai ou mãe?',
}

T = {
# ---------- comum ----------
"The science behind Kinedu · Part 1 of 3": "A ciência por trás do Kinedu · Parte 1 de 3",
"The science behind Kinedu · Part 2 of 3": "A ciência por trás do Kinedu · Parte 2 de 3",
"The science behind Kinedu · Part 3 of 3": "A ciência por trás do Kinedu · Parte 3 de 3",
"About five minutes. Free, no app needed.": "Uns cinco minutos. Grátis e sem baixar nada.",
"Start free": "Comece grátis",
"Take the free assessment": "Faça a avaliação grátis",
"From milestones to a clearer picture": "Dos marcos a uma imagem mais clara",
"How Kinedu’s assessment": "Como a avaliação do Kinedu",
"has evolved.": "evoluiu.",
"Kinedu began with an age-based milestone checklist: one item at a time, with a yes-or-no answer. It was a simple way to record what a baby could already do. We wanted to show more of how those skills develop.": "O Kinedu começou com uma lista de marcos por idade: um item de cada vez, com uma resposta de sim ou não. Era uma forma simples de registrar o que um bebê já sabia fazer. Queríamos mostrar mais de como essas habilidades se desenvolvem.",
"How do the four areas of development connect?": "Como as quatro áreas do desenvolvimento se conectam?",
"Closely linked early on. More distinct as children grow.": "Muito ligadas no início. Mais distintas conforme crescem.",
"We used that insight to look at skills together and build a fuller picture of development.": "Usamos essa descoberta para olhar as habilidades em conjunto e construir uma imagem mais completa do desenvolvimento.",
"Here are three key steps in that journey.": "Estes são três passos importantes desse caminho.",
"Stanford researchers.": "pesquisadores de Stanford.",
"Informed by millions of children.": "Alimentado por milhões de crianças.",
"From the first assessment to research at a much larger scale.": "Da primeira avaliação à pesquisa em uma escala muito maior.",
"We tested the first assessment with 2,135 caregivers to check how well the questions worked. Stanford researcher Michael C. Frank helped review the milestones for children from birth to 24 months.": "Testamos a primeira avaliação com 2.135 cuidadores para verificar como as perguntas funcionavam. O pesquisador de Stanford Michael C. Frank ajudou a revisar os marcos para crianças do nascimento aos 24 meses.",
"Researchers Stenhaug, Ram, and Frank analyzed Kinedu data from 21,861 children. They found that the four areas of development were more closely linked early in life and became more distinct with age. They shared the results in the preprint “The Structure of Developmental Variation in Early Childhood”.": "Os pesquisadores Stenhaug, Ram e Frank analisaram dados do Kinedu de 21.861 crianças. Eles descobriram que as quatro áreas do desenvolvimento estavam mais ligadas no início da vida e ficavam mais distintas com a idade. Compartilharam os resultados no preprint “The Structure of Developmental Variation in Early Childhood”.",
"We expanded the analysis using 281 million validated caregiver observations from 3.5 million children. The broader pattern held: developmental areas were more closely linked early on and became more distinct with age. Our expected ages also lined up with the data, with a median difference of zero months.": "Ampliamos a análise com 281 milhões de observações validadas de cuidadores, de 3,5 milhões de crianças. O padrão geral se manteve: as áreas do desenvolvimento estavam mais ligadas no início e ficavam mais distintas com a idade. Nossas idades esperadas também bateram com os dados, com uma diferença mediana de zero meses.",
"That research helped us map": "Essa pesquisa nos ajudou a mapear",
"how skills develop and connect.": "como as habilidades se desenvolvem e se conectam.",
"We wanted to understand how a skill is taking shape.": "Queríamos entender como uma habilidade vai tomando forma.",
"Walking begins well before those first independent steps:": "Andar começa muito antes daqueles primeiros passos sem ajuda:",
"Answer simple questions about what your baby does.": "Responda perguntas simples sobre o que o seu bebê faz.",
"Questions chosen to capture": "Perguntas escolhidas para captar",
"developing skills.": "as habilidades em desenvolvimento.",
"Walks while holding onto the sofa": "Anda apoiado no sofá",
"Takes steps while holding your hand": "Dá passos segurando a sua mão",
"Takes steps independently": "Dá passos sozinho",
"Every skill in Kinedu is shown along a path like this one:": "Cada habilidade no Kinedu é mostrada ao longo de um caminho como este:",
"Skills that usually appear later than your baby’s current age.": "Habilidades que costumam aparecer mais tarde do que a idade atual do seu bebê.",
"Skills expected around this age that your baby is still working on.": "Habilidades esperadas por volta desta idade que o seu bebê ainda está desenvolvendo.",
"Skills your baby is showing at the expected age.": "Habilidades que o seu bebê mostra na idade esperada.",
"Skills your baby already shows consistently.": "Habilidades que o seu bebê já mostra de forma consistente.",
"A clearer picture of the skills your baby is building": "Uma imagem mais clara das habilidades que o seu bebê está construindo",
"and what may come next.": "e do que pode vir depois.",
"You can answer at home, based on what you see every day. Here’s a sample question from the assessment for 12&#8209;month&#8209;olds:": "Você pode responder em casa, com o que vê todos os dias. Esta é uma pergunta de exemplo da avaliação para bebês de 12 meses:",
"Can your baby stand up from a squat without help?": "Seu bebê fica de pé a partir da posição de cócoras sem ajuda?",
"In our data, caregivers reported this skill in 49.5% of 12-month-olds.": "Nos nossos dados, os cuidadores relataram essa habilidade em 49,5% dos bebês de 12 meses.",
"Does your baby push a button or flip a switch to make something happen?": "Seu bebê aperta um botão ou mexe num interruptor para fazer algo acontecer?",
"Cognitive questions look at how your baby explores and solves problems.": "As perguntas cognitivas observam como o seu bebê explora e resolve problemas.",
"Does your baby wave bye-bye when someone waves first?": "Seu bebê dá tchau com a mão quando alguém acena primeiro?",
"Social-emotional questions look at how your baby connects with people.": "As perguntas socioemocionais observam como o seu bebê se conecta com as pessoas.",
"That’s it.": "Só isso.",
"32 questions like these, in about 5 minutes, adapted to your child’s age.": "32 perguntas como estas, em cerca de 5 minutos, adaptadas à idade do seu filho.",
"This is an example, not an individual child’s result.": "É um exemplo, não o resultado de uma criança em particular.",
"A “not yet” answer doesn’t tell the whole story. We look at it alongside your baby’s age and other answers to understand how their skills are developing.": "Um “ainda não” não conta toda a história. Nós o olhamos junto com a idade do seu bebê e as outras respostas para entender como as habilidades dele estão se desenvolvendo.",
"Your answers help us build a picture.": "Suas respostas nos ajudam a montar uma imagem.",
"We compare your answers with patterns in caregiver reports across ages. Together, they help us understand which skills your baby is developing. You don’t need special training to answer.": "Comparamos as suas respostas com os padrões de relatos de cuidadores em diferentes idades. Juntas, elas nos ajudam a entender quais habilidades o seu bebê está desenvolvendo. Você não precisa de nenhuma preparação especial para responder.",
"“Lifts head while on tummy”: share of caregivers reporting it, by age, across the Kinedu population · Kinedu record, 2020–2023 · a population pattern, not an individual baby’s path": "“Levanta a cabeça de bruços”: porcentagem de cuidadores que relatam isso, por idade, na população do Kinedu · Dados do Kinedu, 2020–2023 · um padrão populacional, não o caminho de um bebê em particular",
"The assessment covers physical, cognitive, language, and social-emotional development. These areas are closely connected early in life and become more distinct as children grow.": "A avaliação cobre o desenvolvimento físico, cognitivo, da linguagem e socioemocional. Essas áreas estão muito conectadas no início da vida e ficam mais distintas conforme as crianças crescem.",
"From holding their head up to jumping on one foot.": "De sustentar a cabeça a pular num pé só.",
"How your child moves and uses their body.": "Como o seu filho se move e usa o corpo.",
"Exploring, solving problems, and playing pretend.": "Explorar, resolver problemas e brincar de faz de conta.",
"How your child learns about the world.": "Como o seu filho aprende sobre o mundo.",
"From babbling to words and sentences.": "Do balbucio às palavras e às frases.",
"How your child understands and communicates.": "Como o seu filho entende e se comunica.",
"Connecting, expressing feelings, and playing with others.": "Conectar-se, expressar sentimentos e brincar com os outros.",
"How your child relates to people and handles emotions.": "Como o seu filho se relaciona com as pessoas e lida com as emoções.",
"What the results mean": "O que os resultados significam",
"What the assessment can tell you,": "O que a avaliação pode dizer a você,",
"and what it can’t.": "e o que não pode.",
"Show which skills your baby is developing": "Mostrar quais habilidades o seu bebê está desenvolvendo",
"and what usually comes next.": "e o que costuma vir depois.",
"Help you prepare questions": "Ajudar você a preparar perguntas",
"for your child’s healthcare professional.": "para o profissional de saúde do seu filho.",
"Put your observations in context": "Colocar as suas observações em contexto",
"using patterns from other children’s development.": "com padrões do desenvolvimento de outras crianças.",
"Provide a diagnosis.": "Dar um diagnóstico.",
"The assessment supports conversations with a qualified healthcare professional.": "A avaliação apoia a conversa com um profissional de saúde qualificado.",
"Evaluate your parenting.": "Avaliar a sua forma de criar.",
"These data describe children’s skills, not the care they receive.": "Esses dados descrevem as habilidades das crianças, não o cuidado que elas recebem.",
"Represent every family.": "Representar todas as famílias.",
"The findings come from families who chose to use Kinedu.": "As descobertas vêm de famílias que escolheram usar o Kinedu.",
"See which skills your baby": "Descubra quais habilidades",
"is building.": "o seu bebê está construindo.",
"In about five minutes, answer questions about everyday behaviors and get a clearer picture of your baby’s developing skills.": "Em cerca de cinco minutos, responda perguntas sobre comportamentos do dia a dia e tenha uma imagem mais clara das habilidades que o seu bebê está desenvolvendo.",
"The science, in three parts": "A ciência, em três partes",
"How Kinedu was built": "Como o Kinedu nasceu",
"The book": "O livro",
"How babies grow": "Como os bebês crescem",
"What you can do as a parent": "O que você pode fazer como pai ou mãe",
"Next: How babies grow →": "Próximo: Como os bebês crescem →",
"Next: What you can do as a parent →": "Próximo: O que você pode fazer como pai ou mãe →",
"← How Kinedu was built": "← Como o Kinedu nasceu",
"← How babies grow": "← Como os bebês crescem",
"Try it free": "Experimente grátis",
"Live classes and the Positive Education masterclass": "Aulas ao vivo e a masterclass de Educação Positiva",
"See live classes": "Ver aulas ao vivo",
"Ask an expert live": "Pergunte a um especialista ao vivo",
"Baby Tracker and the Sleep Habits masterclass": "Baby Tracker e a masterclass de Hábitos de Sono",
"See masterclasses": "Ver masterclasses",
"In the Kinedu app": "No app do Kinedu",
"References to Stanford, Harvard’s Center on the Developing Child and named researchers are for attribution only and do not imply endorsement of Kinedu. Nothing on this page is medical advice.": "As menções a Stanford, ao Center on the Developing Child de Harvard e aos pesquisadores citados são apenas de atribuição e não implicam nenhum endosso ao Kinedu. Nada nesta página é orientação médica.",

# ---------- página 1 ----------
"Studied with Stanford and turned into an assessment that shows what your baby is ready for next. This is the science behind it.": "Estudamos isso com Stanford e transformamos em uma avaliação que mostra para o que o seu bebê está pronto. Esta é a ciência por trás.",
"2013 · Where Kinedu started": "2013 · Onde o Kinedu começou",
"Today · Where Kinedu is": "Hoje · Onde o Kinedu está",
"By 9 months": "Aos 9 meses",
"Sits without support": "Senta sem apoio",
"Passes a toy from hand to hand": "Passa um brinquedo de mão em mão",
"Says “mama” or “dada”": "Diz “mamã” ou “papá”",
"Pulls up to stand": "Fica de pé se segurando",
"yes / no · by age · one line per milestone": "sim / não · por idade · uma linha por marco",
"An old-style milestone checklist by age": "Uma lista de marcos por idade, como as de antigamente",
"How we got there": "Como chegamos até aqui",
"Built by Kinedu. Studied by": "Criado pelo Kinedu. Estudado por",
"caregivers": "pais e mães",
"children": "crianças",
"The rebuild": "A nova avaliação",
"We rebuilt the assessment around": "Redesenhamos a avaliação em torno de",
"a different question.": "uma pergunta diferente.",
"months earlier": "meses antes",
"then": "depois",
"and finally": "e por fim",
"Upcoming": "A caminho",
"Reinforce": "Reforçar",
"On track": "Adquiridas",
"Mastered": "Excelente",
"How the assessment works": "Como funciona a avaliação",
"Why we ask what we ask": "Por que perguntamos o que perguntamos",
"0 mo": "0 m", "3 mo": "3 m", "5 mo": "5 m",
"What the assessment covers": "O que a avaliação cobre",
"414 milestones. 46 skills.": "414 marcos. 46 habilidades.",
"Four areas.": "Quatro áreas.",
"Physical": "Física",
"Cognitive": "Cognitiva",
"Language": "Linguagem",
"Social-emotional": "Socioemocional",
"What it can do": "O que ela pode",
"What it cannot do": "O que ela não pode",
"Research report": "Relatório de pesquisa",
"PDF · full methods and figures": "PDF · métodos e gráficos completos",
"Parent’s guide": "Guia para pais",
"PDF · the findings in plain language": "PDF · as descobertas em linguagem simples",
"Coupling and Differentiation in Early Development · July 2026 · Kinedu supports developmental surveillance. It is not a diagnosis.": "Coupling and Differentiation in Early Development · Julho de 2026 · O Kinedu apoia a vigilância do desenvolvimento. Não é um diagnóstico.",
"Your turn": "Sua vez",
"Developmental surveillance. Not a diagnosis.": "Vigilância do desenvolvimento. Não é um diagnóstico.",
# widget
"Standing up": "Ficar de pé", "Imitation": "Imitação", "Cause and effect": "Causa e efeito",
"Not yet": "Ainda não", "Yes": "Sim",
"Try it with your child →": "Experimente com o seu filho →",
"See the questions again ↺": "Ver as perguntas de novo ↺",
# aria
"Share of babies who lift their head while on tummy, by age: 17% at birth, 48% at 3 months, 93% at 5 months": "Porcentagem de bebês que levantam a cabeça de bruços, por idade: 17% ao nascer, 48% aos 3 meses, 93% aos 5 meses",
"How tightly the four areas move together, by age: 0.49 at 2 months falling to 0.27 at 14 months and staying there": "Quanto as quatro áreas avançam juntas, por idade: 0,49 aos 2 meses, cai para 0,27 aos 14 meses e ali se estabiliza",
"Skills stacked in order: lifts their head at about 3 months, sits at 7, stands at 12, walks at 13": "Habilidades em ordem: levanta a cabeça por volta dos 3 meses, senta aos 7, fica de pé aos 12, anda aos 13",
"Share of children babbling and saying first words, by age: babbling rises first, first words follow": "Porcentagem de crianças que balbuciam e dizem as primeiras palavras, por idade: primeiro sobe o balbucio, depois as palavras",
"Range of normal: learning to walk spans 8 to 13 months, dressing and feeding themselves spans 17 to 39 months": "Faixa do normal: aprender a andar vai dos 8 aos 13 meses; vestir-se e comer sozinho, dos 17 aos 39",
"Windows: exploring objects 1 to 5 months, first steps 8 to 13 months, first words 14 to 25 months": "Janelas: explorar objetos de 1 a 5 meses, primeiros passos de 8 a 13, primeiras palavras de 14 a 25",

# ---------- página 2 ----------
"What 3.5 million children taught us about the first three years.": "O que 3,5 milhões de crianças nos ensinaram sobre os três primeiros anos de vida.",
"Why five": "Por que cinco",
"One · Together": "Um · Tudo junto",
"Five patterns that help": "Cinco padrões que ajudam a",
"explain development.": "explicar o desenvolvimento.",
"Together, these ideas help make sense of how skills connect, when they appear, and why children develop at different paces.": "Juntas, essas ideias ajudam a entender como as habilidades se conectam, quando aparecem e por que cada criança se desenvolve no seu próprio ritmo.",
"Early skills": "As primeiras habilidades",
"develop together.": "se desenvolvem juntas.",
"Holding their head up gives your baby new ways to look around and interact. It’s one example of how movement, learning, communication, and relationships connect.": "Sustentar a cabeça dá ao seu bebê novas maneiras de olhar ao redor e interagir. É um exemplo de como movimento, aprendizado, comunicação e relações se conectam.",
"…and that one skill opens new possibilities:": "…e essa única habilidade abre novas possibilidades:",
"A new view of the room": "Uma nova visão do quarto",
"More ways to respond to your voice": "Mais maneiras de responder à sua voz",
"More opportunities for face-to-face interaction": "Mais oportunidades de interação cara a cara",
"The four areas become more distinct as children grow.": "As quatro áreas ficam mais distintas conforme as crianças crescem.",
"This measure shows how closely progress across the four areas is linked. It falls by almost half during the first year, then remains more stable through the ages shown.": "Esta medida mostra o quanto o progresso nas quatro áreas está ligado. Cai quase pela metade durante o primeiro ano e depois se mantém mais estável nas idades mostradas.",
"closely linked": "muito ligadas",
"more distinct, still linked": "mais distintas, ainda ligadas",
"how linked the four areas are (0 to 1)": "o quanto as quatro áreas estão ligadas (0 a 1)",
"Kinedu record, 2020–2023 · children observed at consecutive ages between 2 and 35 months · technical name: within-child coupling": "Dados do Kinedu, 2020–2023 · crianças observadas em idades consecutivas entre 2 e 35 meses · nome técnico: acoplamento intra-criança",
"Skills build on": "As habilidades se constroem sobre",
"earlier skills.": "habilidades anteriores.",
"Babbling helps lay the groundwork for words. Pulling up to stand helps prepare the way for independent steps. These sequences help us understand what a child may be working toward.": "O balbucio ajuda a preparar o terreno para as palavras. Ficar de pé se segurando ajuda a preparar o caminho para os primeiros passos sozinho. Essas sequências nos ajudam a entender para onde uma criança pode estar avançando.",
"Expected age: when three in four children have the skill · The order is typical, the timing varies · Kinedu record": "Idade esperada: quando três em cada quatro crianças já têm a habilidade · A ordem é típica, o tempo varia · Dados do Kinedu",
"From babbling to first words.": "Do balbucio às primeiras palavras.",
"As children develop early speech, the assessment shifts its focus from babbling to words.": "Conforme as crianças desenvolvem a fala inicial, a avaliação muda o foco do balbucio para as palavras.",
"Average share of “yes” answers across the milestones in each skill group, by age · Kinedu record, 2020–2023 · shaded band ±1 SD": "Média de respostas “sim” entre os marcos de cada grupo de habilidades, por idade · Dados do Kinedu, 2020–2023 · faixa sombreada ±1 DP",
"From first steps to more confident movement.": "Dos primeiros passos a um movimento mais seguro.",
"This skill group includes several milestones, from taking first steps to more advanced movement.": "Este grupo de habilidades inclui vários marcos, desde dar os primeiros passos até movimentos mais avançados.",
"Average share of “yes” answers across the milestones in this skill group, by age · Kinedu record, 2020–2023": "Média de respostas “sim” entre os marcos deste grupo de habilidades, por idade · Dados do Kinedu, 2020–2023",
"Children reach milestones across a wide": "As crianças alcançam os marcos em uma faixa de idades",
"range of ages.": "muito ampla.",
"For some skills, children reach them within a few months of one another. For others, the range spans well over a year, and it tends to widen as children grow.": "Em algumas habilidades, as crianças chegam lá com poucos meses de diferença entre si. Em outras, a faixa abrange bem mais de um ano, e tende a se ampliar conforme crescem.",
"a reference point, not a deadline.": "um ponto de referência, não um prazo.",
"A learning window": "Uma janela de aprendizado não é",
"isn’t a countdown.": "uma contagem regressiva.",
"The chart shows when reports of these skills become more common in our data. These age ranges describe a pattern, not a deadline for an individual child.": "O gráfico mostra quando os relatos dessas habilidades se tornam mais comuns nos nossos dados. Essas faixas de idade descrevem um padrão, não um prazo para uma criança em particular.",
"Today’s assessment doesn’t tell your child’s": "A avaliação de hoje não conta todo",
"whole future.": "o futuro do seu filho.",
"A child’s current skill level tells us little about how quickly they’ll progress next. Where they are today and their pace of development are different things.": "O nível atual de habilidades de uma criança diz pouco sobre a velocidade com que ela vai avançar depois. Onde ela está hoje e o seu ritmo de desenvolvimento são coisas diferentes.",
"Each assessment captures a moment in your child’s development. Checking in again helps you see what has changed.": "Cada avaliação captura um momento do desenvolvimento do seu filho. Fazer de novo ajuda a ver o que mudou.",
"at age 2, it says little about where they stand": "aos 2 anos, diz pouco sobre onde ele está",
"3 months later, it still says a lot about where they stand": "3 meses depois, ainda diz muito sobre onde ele está",
"Checking in again:": "Avaliar de novo:",
"An assessment is a photograph: one taken at 3 months says little by age 2, one taken at 2 years still says a lot three months later, so check in again every few months": "Uma avaliação é uma fotografia: uma feita aos 3 meses diz pouco aos 2 anos, uma feita aos 2 anos ainda diz muito três meses depois, então avalie de novo a cada poucos meses",
"In this analysis, current skill level explained about 1.5% of the variation in subsequent developmental pace.": "Nesta análise, o nível atual de habilidades explicou cerca de 1,5% da variação no ritmo de desenvolvimento posterior.",
"Lifts their head": "Levanta a cabeça",
"The same signal across 3.5 million children: 0.49 at 2 months, 0.27 after the first year, and never zero.": "O mesmo sinal em 3,5 milhões de crianças: 0,49 aos 2 meses, 0,27 depois do primeiro ano, e nunca zero.",
"child age, months": "idade em meses",
"Proof": "A prova",
"Two · In order": "Dois · Em ordem",
"≈ 3 mo": "≈ 3 m", "≈ 7 mo": "≈ 7 m", "≈ 12 mo": "≈ 12 m", "≈ 13 mo": "≈ 13 m",
"Sits": "Senta", "Stands": "Fica de pé", "Walks": "Anda",
"Babbling →": "Balbucio →",
"First words": "Primeiras palavras",
"We checked every expected age against what 3.5 million children actually did. The typical difference: zero months.": "Comparamos cada idade esperada com o que 3,5 milhões de crianças realmente fizeram. A diferença típica: zero meses.",
"Three · Wide": "Três · Amplo",
"Learning to walk": "Aprender a andar",
"8–13 mo · a 5-month range": "8–13 m · uma faixa de 5 meses",
"Dressing and feeding themselves": "Vestir-se e comer sozinho",
"17–39 mo · a 22-month range": "17–39 m · uma faixa de 22 meses",
"42 months": "42 meses",
"8–13 mo · 5 months wide": "8–13 m · faixa de 5 meses",
"17–39 mo · 22 months wide": "17–39 m · faixa de 22 meses",
"An expected age is": "Uma idade esperada é",
"Four · Windows": "Quatro · Janelas",
"Exploring objects": "Explorar objetos",
"1–5 mo": "1–5 m", "8–13 mo": "8–13 m", "14–25 mo": "14–25 m",
"First steps": "Primeiros passos",
"Five · Unpredictable": "Cinco · Imprevisível",
"In short": "Em resumo",
"Instead of asking whether your baby is on time, Kinedu helps you ask": "Em vez de perguntar se o seu bebê está no tempo certo, o Kinedu ajuda você a perguntar",
"what she is ready for.": "para o que ele está pronto.",
"Read the room for you.": "Responder por você.",
"About 11% of a reading is how the caregiver answers, not the child. We correct for it, and we would rather tell you than not.": "Cerca de 11% de uma leitura depende de como quem cuida do bebê responde, não do bebê. Corrigimos isso, e preferimos contar a você.",

"Walking": "Andar",
"An assessment is a photograph, not a prophecy.": "Uma avaliação é uma fotografia, não uma profecia.",
"your baby’s age, months": "idade do seu bebê, em meses",
"Assessment at 3 months": "Avaliação aos 3 meses",
"Assessment at 2 years": "Avaliação aos 2 anos",
"a new picture every few months": "uma foto nova a cada poucos meses",
# ---------- página 3 ----------
"Four things that are actually in your hands.": "Quatro coisas que estão de verdade nas suas mãos.",
"Where this comes from": "De onde isso vem",
"One": "Um", "Two": "Dois", "Three": "Três", "Four": "Quatro",
"Play": "Brincadeira", "Relationships": "Vínculo", "Stress": "Estresse", "Predictability": "Previsibilidade",
"Everyday moments give you": "Os momentos do dia a dia dão a você",
"ways to help.": "maneiras de ajudar.",
"Kinedu’s data help us understand how children’s skills develop. The ideas on this page come from broader research on parenting and child development. They focus on four parts of everyday life:": "Os dados do Kinedu nos ajudam a entender como as habilidades das crianças se desenvolvem. As ideias desta página vêm de uma pesquisa mais ampla sobre criação e desenvolvimento infantil. Elas se concentram em quatro partes da vida cotidiana:",
"Follow their curiosity. Join the back-and-forth.": "Siga a curiosidade dele. Entre no vai e vem.",
"Warmth, connection, and clear limits.": "Carinho, conexão e limites claros.",
"Help them through difficult moments.": "Acompanhe nos momentos difíceis.",
"Build routines they can recognize.": "Crie rotinas que ele possa reconhecer.",
"Play starts with the back-and-forth": "A brincadeira começa com o vai e vem",
"between you.": "entre vocês.",
"Your baby makes a sound. You respond. They respond again. Researchers call these back-and-forth exchanges “serve and return.” Your face, voice, and attention are part of the interaction.": "Seu bebê faz um som. Você responde. Ele responde de novo. Os pesquisadores chamam essas trocas de vai e vem de “servir e devolver”. Seu rosto, sua voz e sua atenção fazem parte da interação.",
"smile or talk back": "sorri ou fala com ele",
"responds": "responde",
"As your child grows, your role in play changes. Sometimes they lead. Sometimes you offer a prompt, introduce a rule, or show them how something works.": "Conforme o seu filho cresce, o seu papel na brincadeira muda. Às vezes ele conduz. Às vezes você sugere algo, introduz uma regra ou mostra como algo funciona.",
"Your child chooses what to explore and how to use it. There’s room to invent, experiment, and follow their curiosity.": "Seu filho escolhe o que explorar e como usar. Há espaço para inventar, experimentar e seguir a própria curiosidade.",
"You create an opportunity or offer a prompt, while your child leads the exploration. With colored cups, for example, you might invite them to sort or compare.": "Você cria uma oportunidade ou sugere algo, e o seu filho conduz a exploração. Com copos coloridos, por exemplo, você pode convidá-lo a separar ou comparar.",
"Simple games give children practice taking turns, following rules, and trying again.": "Jogos simples dão às crianças prática em esperar a vez, seguir regras e tentar de novo.",
"You show your child how to do a specific task, then give them a chance to try.": "Você mostra ao seu filho como fazer uma tarefa específica e depois dá a ele a chance de tentar.",
"Choose the approach that fits": "Escolha a abordagem que combina com",
"what your child is exploring.": "o que o seu filho está explorando.",
"Daily activity ideas": "Ideias de atividades diárias",
"Short videos that show you how to try activities with your baby.": "Vídeos curtos que mostram como fazer atividades com o seu bebê.",
"Harvard’s Center on the Developing Child describes three types of stress response: positive, tolerable, and toxic. The intensity, duration, and support available to a child matter.": "O Center on the Developing Child de Harvard descreve três tipos de resposta ao estresse: positiva, tolerável e tóxica. A intensidade, a duração e o apoio disponível para a criança fazem diferença.",
"A brief challenge, with support from a caring adult, followed by a return to calm.": "Um desafio breve, com o apoio de um adulto que cuida, seguido de um retorno à calma.",
"A more serious difficulty. Supportive relationships help the child cope and recover.": "Uma dificuldade mais séria. Relações de apoio ajudam a criança a lidar com ela e se recuperar.",
"Prolonged or excessive stress without adequate adult support. This can affect development and long-term health.": "Estresse prolongado ou excessivo sem o apoio adequado de um adulto. Isso pode afetar o desenvolvimento e a saúde a longo prazo.",
"One · Play": "Um · Brincadeira",
"Your baby": "Seu bebê",
"coos": "balbucia",
"You": "Você",
"…and so on, back and forth": "…e assim, de novo e de novo",
"Your baby in charge": "Seu bebê manda",
"You in charge": "Você dirige",
"Your baby leads": "Seu bebê conduz",
"You set it up, they run it": "Você prepara, o bebê conduz",
"Rules, with room to play": "Regras, mas com espaço",
"You lead": "Você dirige",
"Free play": "Brincadeira livre",
"Guided play": "Brincadeira guiada",
"Games": "Jogos",
"Direct instruction": "Instrução direta",
"Two · Relationships": "Dois · Vínculo",
"Warmth and clear limits": "Carinho e limites claros",
"can go together.": "podem andar juntos.",
"You can respond to your child’s feelings while keeping a clear limit. The goal is to offer support and expectations that fit their age.": "Você pode responder ao que o seu filho sente e, ao mesmo tempo, manter um limite claro. A ideia é oferecer apoio e expectativas adequadas à idade dele.",
"You can say no with care.": "Você pode dizer não com carinho.",
"Your child can feel upset about a limit and still receive your comfort and support.": "Seu filho pode ficar chateado com um limite e ainda assim receber o seu conforto e apoio.",
"Keep the limit. Stay connected.": "Mantenha o limite. Mantenha a conexão.",
"Acknowledge the feeling and explain the boundary in simple words.": "Reconheça o sentimento e explique o limite com palavras simples.",
"Help them find their calm.": "Ajude a encontrar a calma.",
"Offer a calm voice and support while they learn to handle strong feelings.": "Ofereça uma voz tranquila e apoio enquanto ele aprende a lidar com emoções intensas.",
"You won’t get every moment right. You can reconnect and try again.": "Você não vai acertar em todos os momentos. Sempre dá para se reconectar e tentar de novo.",
"Learn ways to set limits with care and respond to tantrums, with guidance from child psychologists.": "Aprenda maneiras de colocar limites com carinho e responder às birras, com a orientação de psicólogas infantis.",
"Your support can help your child": "O seu apoio pode ajudar o seu filho",
"through difficult moments.": "a atravessar os momentos difíceis.",
"Bring your questions to a live class.": "Traga as suas perguntas para uma aula ao vivo.",
"Three · Stress": "Três · Estresse",
"Not all stress is": "Nem todo estresse",
"the same.": "é igual.",
"Positive": "Positivo",
"Tolerable": "Tolerável",
"Toxic": "Tóxico",
"Connect. Guide. Protect. Repeat.": "Conecte. Guie. Proteja. Repita.",
"Find ideas for putting these principles into practice with your child.": "Encontre ideias para colocar esses princípios em prática com o seu filho.",
"Explore Kinedu": "Explore o Kinedu",
"Four · Predictability": "Quatro · Previsibilidade",
"Familiar routines help your child know": "Rotinas conhecidas ajudam o seu filho a saber",
"what comes next.": "o que vem depois.",
"When our team asked Phil Fisher, of the Stanford Center on Early Childhood, what advice he would give parents, he emphasized predictability: familiar routines children can count on.": "Quando nossa equipe perguntou a Phil Fisher, do Stanford Center on Early Childhood, que conselho daria aos pais, ele destacou a previsibilidade: rotinas conhecidas com as quais as crianças podem contar.",
"Familiar patterns around meals, play, and bedtime can make the day easier to recognize. A routine can be simple and still leave room to adapt.": "Padrões conhecidos em torno das refeições, da brincadeira e da hora de dormir tornam o dia mais fácil de reconhecer. Uma rotina pode ser simples e ainda deixar espaço para se adaptar.",
"A familiar rhythm, day after day": "Um ritmo conhecido, dia após dia",
"Keep it simple, familiar,": "Que seja simples, conhecida",
"and flexible.": "e flexível.",
"Keep track of feeds, naps, and diaper changes in one place. Explore bedtime routines in the Sleep Habits masterclass.": "Acompanhe mamadas, sonecas e trocas de fralda em um só lugar. Explore rotinas de sono na masterclass de Hábitos de Sono.",
"Wake up": "Acordar", "Meals": "Refeições", "Play": "Brincar", "Nap": "Soneca", "Bath": "Banho", "Bedtime": "Dormir",
"None of this asks you to become a different parent.": "Nada disso pede que você seja outro tipo de pai ou mãe.",
"Be there on purpose, in four ways. Kinedu shows you which one this week calls for.": "Só estar presente de propósito, de quatro maneiras. O Kinedu diz qual delas o seu bebê precisa nesta semana.",
}

def to_pt(html, path): return localize(html, path, 'pt', META, H1, T)
