# -*- coding: utf-8 -*-
"""Versão em português (Brasil) das 3 páginas de Science. Mesmas chaves EN que es.py."""
from l10n import localize

META = {
 "/science": ("A ciência por trás do Kinedu: como chegamos até aqui | Kinedu",
              "Construímos o Kinedu vendo 3,5 milhões de crianças crescerem. O que aprendemos virou a base do app: de uma lista de marcos a uma avaliação que mostra o que está surgindo.",
              "O Kinedu foi construído sobre como 3,5 milhões de bebês realmente cresceram | Kinedu"),
 "/science-what-we-know": ("Cinco coisas que aprendemos sobre como os bebês se desenvolvem | Kinedu",
              "O que os dados de 3,5 milhões de crianças mostram sobre os primeiros anos: tudo cresce junto, as habilidades vêm em ordem, a faixa é ampla e nenhum gráfico prevê o seu filho.",
              "Cinco coisas que aprendemos sobre como os bebês se desenvolvem | Kinedu"),
 "/science-what-you-can-do": ("Quatro maneiras de apoiar o desenvolvimento do seu filho | Kinedu",
              "Brincadeira, vínculo, estresse e previsibilidade: as quatro coisas para as quais a evidência sempre aponta, e o que um pai ou uma mãe pode fazer com elas.",
              "Quatro maneiras de apoiar o desenvolvimento do seu filho | Kinedu"),
}

H1 = {
 'How we built a clearer picture of <span class="gradient-shift">your baby’s development.</span>': 'Como construímos uma imagem mais clara <span class="gradient-shift">do desenvolvimento do seu bebê.</span>',
 'Five things we’ve learned about <span class="gradient-shift">how babies develop.</span>': 'Cinco coisas que aprendemos sobre <span class="gradient-shift">como os bebês se desenvolvem.</span>',
 'Four ways to support your child’s <span class="gradient-shift">development.</span>': 'Quatro maneiras de apoiar o <span class="gradient-shift">desenvolvimento</span> do seu filho.',
}

T = {
'What data from 3.5 million children show about the early years.': 'O que os dados de 3,5 milhões de crianças mostram sobre os primeiros anos.',
'Your child’s pace': 'O ritmo do seu filho',
'can change.': 'pode mudar.',
'The chart below looks at a different question: how much an earlier assessment tells us about a child’s skill level later on.': 'O gráfico abaixo olha para uma pergunta diferente: quanto uma avaliação anterior nos diz sobre o nível de habilidades de uma criança mais adiante.',
'Explore the Kinedu app': 'Explore o app do Kinedu',
'Average share of caregiver “yes” answers across milestones in the babbling and first words skill groups, by age.': 'Média de respostas “sim” dos cuidadores nos marcos dos grupos de balbucio e primeiras palavras, por idade.',
'Average share of caregiver “yes” answers across milestones in the walking skill group, by age.': 'Média de respostas “sim” dos cuidadores nos marcos do grupo de andar, por idade.',
'Age ranges shown for walking and self-care skill groups. See the chart caption for how the ranges are defined.': 'Faixas de idade dos grupos de andar e de autocuidado. A legenda do gráfico explica como as faixas são definidas.',
'Each bar spans the ages at which 25% and 75% of children in the Kinedu record were reported with the milestones in that skill group.': 'Cada barra vai da idade em que 25% das crianças do registro do Kinedu foram relatadas com os marcos desse grupo até a idade em que 75% foram.',
# ---------- comum ----------
"The science behind Kinedu · Part 1 of 3": "A ciência por trás do Kinedu · Parte 1 de 3",
"The science behind Kinedu · Part 2 of 3": "A ciência por trás do Kinedu · Parte 2 de 3",
"The science behind Kinedu · Part 3 of 3": "A ciência por trás do Kinedu · Parte 3 de 3",
"About five minutes. Free, no app needed.": "Uns cinco minutos. Grátis e sem baixar nada.",
"Take the free assessment": "Faça a avaliação grátis",
"A checklist of milestones by age.": "Uma lista de marcos por idade.",
"You can answer at home, based on what you see every day. Here’s a sample question from the assessment for 12&#8209;month&#8209;olds:": "Você pode responder em casa, com o que vê todos os dias. Esta é uma pergunta de exemplo da avaliação para bebês de 12 meses:",
"We consider each answer alongside your baby’s age and other skills.": "Consideramos cada resposta junto com a idade do seu bebê e as outras habilidades dele.",
"How we interpret your answers": "Como interpretamos as suas respostas",
"Answer simple questions about what your baby does.": "Responda perguntas simples sobre o que o seu bebê faz.",
"That’s it.": "Só isso.",
"Built with insights from 3.5 million children, so you can see the skills your baby is building and what may come next.": "Construída com o que aprendemos de 3,5 milhões de crianças, para você ver as habilidades que o seu bebê está construindo e o que pode vir depois.",
"Why we built it": "Por que criamos o Kinedu",
"How skills develop": "Como as habilidades se desenvolvem",
"How you can support them": "Como você pode apoiá-las",
"When your baby lifts their head, they can see more of the world and find new ways to respond to you. It’s one example of how movement, learning, communication, and relationships connect.": "Quando o seu bebê levanta a cabeça, ele vê mais do mundo e encontra novas formas de responder a você. É um exemplo de como movimento, aprendizado, comunicação e relações se conectam.",
"Sees more of the room": "Vê mais do quarto",
"Can turn toward your voice": "Consegue se virar para a sua voz",
"Has more face-to-face moments with you": "Tem mais momentos cara a cara com você",
"Early on, the four areas grow closely together.": "No começo, as quatro áreas crescem bem juntas.",
"As children get older, each area begins to follow its own path, while still influencing the others.": "Conforme as crianças crescem, cada área começa a seguir o próprio caminho, sem deixar de influenciar as outras.",
"What your child is doing today doesn’t tell us how quickly the next skill will come. Where they are today and their pace of development are different things.": "O que o seu filho faz hoje não nos diz com que rapidez a próxima habilidade vai chegar. Onde ele está hoje e o ritmo do desenvolvimento dele são coisas diferentes.",
"An assessment is a snapshot, not a prediction.": "Uma avaliação é um retrato do momento, não uma previsão.",
"Reads each answer alongside your baby’s age and other skills.": "Lê cada resposta junto com a idade do seu bebê e as outras habilidades dele.",
"Looks for what’s just beginning, not only what’s already mastered.": "Procura o que está só começando, não só o que ele já domina.",
"Expected ages checked against 3.5 million children.": "Idades esperadas verificadas com 3,5 milhões de crianças.",
"There’s no single right way to play.": "Não existe um único jeito certo de brincar.",
"Choose what fits the moment.": "Escolha o que combina com o momento.",
"Short videos with simple activities you can try together.": "Vídeos curtos com atividades simples para fazer juntos.",
"You can comfort your child without changing the limit. They can be upset and still feel safe, loved, and supported.": "Você pode consolar o seu filho sem mudar o limite. Ele pode estar chateado e ainda assim se sentir seguro, amado e apoiado.",
"Supporting your child doesn’t have to mean adding more to your day. Four everyday ways to play, connect, help them through stress, and build familiar routines.": "Apoiar o seu filho não precisa significar colocar mais coisas no seu dia. Quatro formas do dia a dia de brincar, conectar, ajudá-lo no estresse e construir rotinas familiares.",
"Want to go deeper?": "Quer ir mais fundo?",
"Live classes": "Aulas ao vivo",
"Positive Education masterclass": "Masterclass de Educação Positiva",
"Sleep Habits masterclass": "Masterclass de Hábitos de Sono",
"More than a milestone checklist": "Mais que uma lista de marcos",
"From checking milestones to seeing how": "De marcar marcos a ver como",
"skills grow together.": "as habilidades crescem juntas.",
"Then · 2013": "Antes · 2013",
"Now · today": "Agora · hoje",
"A connected view of how your baby’s skills are taking shape.": "Uma visão conectada de como as habilidades do seu bebê vão tomando forma.",
"Shaped by data from millions of children.": "Moldado com dados de milhões de crianças.",
"Here’s how the assessment grew from its first version to the one families use today.": "Foi assim que a avaliação cresceu, da primeira versão até a que as famílias usam hoje.",
"We tested the first version with 2,135 caregivers to make sure the questions were clear and useful. Stanford researcher Michael C. Frank also helped us review milestones from birth to 24 months.": "Testamos a primeira versão com 2.135 cuidadores para garantir que as perguntas fossem claras e úteis. O pesquisador de Stanford Michael C. Frank também nos ajudou a revisar os marcos do nascimento aos 24 meses.",
"Stanford researchers studied Kinedu data from 21,861 children. They found that developmental skills are closely connected early in life and become more distinct as children grow.": "Pesquisadores de Stanford estudaram dados do Kinedu de 21.861 crianças. Eles descobriram que as habilidades do desenvolvimento estão muito conectadas no início da vida e ficam mais distintas conforme as crianças crescem.",
"Read the Stanford research →": "Leia a pesquisa de Stanford →",
"We looked again, this time at 281 million caregiver observations from 3.5 million children. The same pattern held: skills are more connected early on and become more distinct with age.": "Olhamos de novo, desta vez para 281 milhões de observações de cuidadores de 3,5 milhões de crianças. O padrão se repetiu: as habilidades estão mais conectadas no início e ficam mais distintas com a idade.",
"That research helped us understand not just when skills appear,": "Essa pesquisa nos ajudou a entender não só quando as habilidades aparecem,",
"but how they build on one another.": "mas como elas se constroem umas sobre as outras.",
"One milestone doesn’t tell": "Um marco não conta",
"the whole story.": "a história toda.",
"Instead of asking only whether a skill has appeared, we look at how it’s taking shape over time. Walking, for example, begins long before those first independent steps:": "Em vez de perguntar só se uma habilidade já apareceu, olhamos como ela vai tomando forma com o tempo. Andar, por exemplo, começa muito antes daqueles primeiros passos sem ajuda:",
"It often starts here": "Costuma começar aqui",
"Next": "Depois",
"Then": "Então",
"Eventually": "Com o tempo",
"See where each skill is taking shape,": "Veja em que ponto cada habilidade está tomando forma,",
"not just whether it has happened yet.": "não só se ela já aconteceu.",
"In about five minutes, tell us what you’re seeing day to day. We’ll help you understand what’s taking shape and what may come next.": "Em cerca de cinco minutos, conte o que você vê no dia a dia. A gente ajuda você a entender o que está tomando forma e o que pode vir depois.",
"Next: How skills develop →": "Próximo: Como as habilidades se desenvolvem →",
"Next: How you can support them →": "Próximo: Como você pode apoiá-las →",
"← Why we built it": "← Por que criamos o Kinedu",
"← How skills develop": "← Como as habilidades se desenvolvem",
"Stanford researchers.": "pesquisadores de Stanford.",
"Walks while holding onto the sofa": "Anda apoiado no sofá",
"Takes steps while holding your hand": "Dá passos segurando a sua mão",
"Takes steps independently": "Dá passos sozinho",
"Every skill in Kinedu is shown along a path like this one:": "Cada habilidade no Kinedu é mostrada ao longo de um caminho como este:",
"Usually develops at a later age.": "Costuma se desenvolver em uma idade maior.",
"Expected around this age; still developing.": "Esperada por volta desta idade; ainda em desenvolvimento.",
"Showing at the expected age.": "Aparece na idade esperada.",
"Showing consistently.": "Aparece de forma consistente.",
"and what may come next.": "e do que pode vir depois.",
"Can your baby stand up from a squat without help?": "Seu bebê fica de pé a partir da posição de cócoras sem ajuda?",
"In our data, caregivers reported this skill in 49.5% of 12-month-olds.": "Nos nossos dados, os cuidadores relataram essa habilidade em 49,5% dos bebês de 12 meses.",
"Does your baby push a button or flip a switch to make something happen?": "Seu bebê aperta um botão ou mexe num interruptor para fazer algo acontecer?",
"Cognitive questions look at how your baby explores and solves problems.": "As perguntas cognitivas observam como o seu bebê explora e resolve problemas.",
"Does your baby wave bye-bye when someone waves first?": "Seu bebê dá tchau com a mão quando alguém acena primeiro?",
"Social-emotional questions look at how your baby connects with people.": "As perguntas socioemocionais observam como o seu bebê se conecta com as pessoas.",
"That’s it.": "Só isso.",
"32 questions like these, in about 5 minutes, adapted to your child’s age.": "32 perguntas como estas, em cerca de 5 minutos, adaptadas à idade do seu filho.",
"This is an example, not an individual child’s result.": "É um exemplo, não o resultado de uma criança em particular.",
"We compare your answers with patterns in caregiver reports across ages. Together, they help us understand which skills your baby is developing. You don’t need special training to answer.": "Comparamos as suas respostas com os padrões de relatos de cuidadores em diferentes idades. Juntas, elas nos ajudam a entender quais habilidades o seu bebê está desenvolvendo. Você não precisa de nenhuma preparação especial para responder.",
"“Lifts head while on tummy”: share of caregivers reporting it, by age, across the Kinedu population · Kinedu record, 2020–2023 · a population pattern, not an individual baby’s path": "“Levanta a cabeça de bruços”: porcentagem de cuidadores que relatam isso, por idade, na população do Kinedu · Dados do Kinedu, 2020–2023 · um padrão populacional, não o caminho de um bebê em particular",
"From holding their head up to jumping on one foot.": "De sustentar a cabeça a pular num pé só.",
"Exploring, solving problems, and playing pretend.": "Explorar, resolver problemas e brincar de faz de conta.",
"From babbling to words and sentences.": "Do balbucio às palavras e às frases.",
"Connecting, expressing feelings, and playing with others.": "Conectar-se, expressar sentimentos e brincar com os outros.",
"What the results mean": "O que os resultados significam",
"What the assessment can tell you,": "O que a avaliação pode dizer a você,",
"and what it can’t.": "e o que não pode.",
"Show which skills your baby is developing": "Mostrar quais habilidades o seu bebê está desenvolvendo",
"and what usually comes next.": "e o que costuma vir depois.",
"Help you prepare questions": "Ajudar você a preparar perguntas",
"for your child’s healthcare professional.": "para o profissional de saúde do seu filho.",
"Put your observations in context": "Colocar as suas observações em contexto",
"using patterns from other children’s development.": "com padrões do desenvolvimento de outras crianças.",
"Provide a diagnosis.": "Dar um diagnóstico.",
"The assessment supports conversations with a qualified healthcare professional.": "A avaliação apoia a conversa com um profissional de saúde qualificado.",
"Evaluate your parenting.": "Avaliar a sua forma de criar.",
"These data describe children’s skills, not the care they receive.": "Esses dados descrevem as habilidades das crianças, não o cuidado que elas recebem.",
"Represent every family.": "Representar todas as famílias.",
"The findings come from families who chose to use Kinedu.": "As descobertas vêm de famílias que escolheram usar o Kinedu.",
"See which skills your baby": "Descubra quais habilidades",
"is building.": "o seu bebê está construindo.",
"The science, in three parts": "A ciência, em três partes",
"Try it free": "Experimente grátis",
"In the Kinedu app": "No app do Kinedu",

# ---------- página 1 ----------
"By 9 months": "Aos 9 meses",
"Sits without support": "Senta sem apoio",
"Passes a toy from hand to hand": "Passa um brinquedo de mão em mão",
"Says “mama” or “dada”": "Diz “mamã” ou “papá”",
"Pulls up to stand": "Fica de pé se segurando",
"yes / no · by age · one line per milestone": "sim / não · por idade · uma linha por marco",
"An old-style milestone checklist by age": "Uma lista de marcos por idade, como as de antigamente",
"How we got there": "Como chegamos até aqui",
"Built by Kinedu. Studied by": "Criado pelo Kinedu. Estudado por",
"caregivers": "pais e mães",
"children": "crianças",
"The rebuild": "A nova avaliação",
"then": "depois",
"Upcoming": "A caminho",
"Reinforce": "Reforçar",
"On track": "Adquiridas",
"Mastered": "Excelente",
"How the assessment works": "Como funciona a avaliação",
"0 mo": "0 m", "3 mo": "3 m", "5 mo": "5 m",
"What the assessment covers": "O que a avaliação cobre",
"414 milestones.": "414 marcos.",
"46 skills.": "46 habilidades.",
"Four areas.": "Quatro áreas.",
"Physical": "Física",
"Cognitive": "Cognitiva",
"Language": "Linguagem",
"Social-emotional": "Socioemocional",
"What it can do": "O que ela pode",
"What it cannot do": "O que ela não pode",
"Research report": "Relatório de pesquisa",
"PDF · full methods and figures": "PDF · métodos e gráficos completos",
"Parent’s guide": "Guia para pais",
"PDF · the findings in plain language": "PDF · as descobertas em linguagem simples",
"Coupling and Differentiation in Early Development · July 2026 · Kinedu supports developmental surveillance. It is not a diagnosis.": "Coupling and Differentiation in Early Development · Julho de 2026 · O Kinedu apoia a vigilância do desenvolvimento. Não é um diagnóstico.",
"Your turn": "Sua vez",
"Developmental surveillance. Not a diagnosis.": "Vigilância do desenvolvimento. Não é um diagnóstico.",
# widget
"Standing up": "Ficar de pé", "Imitation": "Imitação", "Cause and effect": "Causa e efeito",
"Not yet": "Ainda não", "Yes": "Sim",
"Try it with your child →": "Experimente com o seu filho →",
"See the questions again ↺": "Ver as perguntas de novo ↺",
# aria
"Share of babies who lift their head while on tummy, by age: 17% at birth, 48% at 3 months, 93% at 5 months": "Porcentagem de bebês que levantam a cabeça de bruços, por idade: 17% ao nascer, 48% aos 3 meses, 93% aos 5 meses",
"How tightly the four areas move together, by age: 0.49 at 2 months falling to 0.27 at 14 months and staying there": "Quanto as quatro áreas avançam juntas, por idade: 0,49 aos 2 meses, cai para 0,27 aos 14 meses e ali se estabiliza",
"Skills stacked in order: lifts their head at about 3 months, sits at 7, stands at 12, walks at 13": "Habilidades em ordem: levanta a cabeça por volta dos 3 meses, senta aos 7, fica de pé aos 12, anda aos 13",
"Windows: exploring objects 1 to 5 months, first steps 8 to 13 months, first words 14 to 25 months": "Janelas: explorar objetos de 1 a 5 meses, primeiros passos de 8 a 13, primeiras palavras de 14 a 25",

# ---------- página 2 ----------
"Why five": "Por que cinco",
"One · Together": "Um · Tudo junto",
"Five patterns that help": "Cinco padrões que ajudam a",
"explain development.": "explicar o desenvolvimento.",
"Together, these ideas help make sense of how skills connect, when they appear, and why children develop at different paces.": "Juntas, essas ideias ajudam a entender como as habilidades se conectam, quando aparecem e por que cada criança se desenvolve no seu próprio ritmo.",
"Early skills": "As primeiras habilidades",
"develop together.": "se desenvolvem juntas.",
"…and that one skill opens new possibilities:": "…e essa única habilidade abre novas possibilidades:",
"closely linked": "muito ligadas",
"more distinct, still linked": "mais distintas, ainda ligadas",
"how linked the four areas are (0 to 1)": "o quanto as quatro áreas estão ligadas (0 a 1)",
"The connection between the four areas falls by almost half during the first year, then remains more stable through the ages shown · Kinedu record, 2020–2023 · children observed at consecutive ages between 2 and 35 months · technical name: within-child coupling": "A conexão entre as quatro áreas cai quase pela metade no primeiro ano e depois se mantém mais estável nas idades mostradas · Dados do Kinedu, 2020–2023 · crianças observadas em idades consecutivas entre 2 e 35 meses · nome técnico: acoplamento intra-criança",
"Skills build on": "As habilidades se constroem sobre",
"earlier skills.": "habilidades anteriores.",
"Babbling helps lay the groundwork for words. Pulling up to stand helps prepare the way for independent steps. These sequences help us understand what a child may be working toward.": "O balbucio ajuda a preparar o terreno para as palavras. Ficar de pé se segurando ajuda a preparar o caminho para os primeiros passos sozinho. Essas sequências nos ajudam a entender para onde uma criança pode estar avançando.",
"Expected age: when three in four children have the skill · The order is typical, the timing varies · Kinedu record": "Idade esperada: quando três em cada quatro crianças já têm a habilidade · A ordem é típica, o tempo varia · Dados do Kinedu",
"From babbling to first words.": "Do balbucio às primeiras palavras.",
"As children develop early speech, the assessment shifts its focus from babbling to words.": "Conforme as crianças desenvolvem a fala inicial, a avaliação muda o foco do balbucio para as palavras.",
"Average share of “yes” answers across the milestones in each skill group, by age · Kinedu record, 2020–2023 · shaded band ±1 SD": "Média de respostas “sim” entre os marcos de cada grupo de habilidades, por idade · Dados do Kinedu, 2020–2023 · faixa sombreada ±1 DP",
"From first steps to more confident movement.": "Dos primeiros passos a um movimento mais seguro.",
"This skill group includes several milestones, from taking first steps to more advanced movement.": "Este grupo de habilidades inclui vários marcos, desde dar os primeiros passos até movimentos mais avançados.",
"Average share of “yes” answers across the milestones in this skill group, by age · Kinedu record, 2020–2023": "Média de respostas “sim” entre os marcos deste grupo de habilidades, por idade · Dados do Kinedu, 2020–2023",
"Children reach milestones across a wide": "As crianças alcançam os marcos em uma faixa de idades",
"range of ages.": "muito ampla.",
"For some skills, children reach them within a few months of one another. For others, the range spans well over a year, and it tends to widen as children grow.": "Em algumas habilidades, as crianças chegam lá com poucos meses de diferença entre si. Em outras, a faixa abrange bem mais de um ano, e tende a se ampliar conforme crescem.",
"a reference point, not a deadline.": "um ponto de referência, não um prazo.",
"A learning window": "Uma janela de aprendizado não é",
"isn’t a countdown.": "uma contagem regressiva.",
"The chart shows when reports of these skills become more common in our data. These age ranges describe a pattern, not a deadline for an individual child.": "O gráfico mostra quando os relatos dessas habilidades se tornam mais comuns nos nossos dados. Essas faixas de idade descrevem um padrão, não um prazo para uma criança em particular.",
"Each assessment captures a moment in your child’s development. Checking in again helps you see what has changed.": "Cada avaliação captura um momento do desenvolvimento do seu filho. Fazer de novo ajuda a ver o que mudou.",
"at age 2, it says little about where they stand": "aos 2 anos, diz pouco sobre onde ele está",
"3 months later, it still says a lot about where they stand": "3 meses depois, ainda diz muito sobre onde ele está",
"Checking in again:": "Avaliar de novo:",
"An assessment is a photograph: one taken at 3 months says little by age 2, one taken at 2 years still says a lot three months later, so check in again every few months": "Uma avaliação é uma fotografia: uma feita aos 3 meses diz pouco aos 2 anos, uma feita aos 2 anos ainda diz muito três meses depois, então avalie de novo a cada poucos meses",
"In this analysis, current skill level explained about 1.5% of the variation in subsequent developmental pace.": "Nesta análise, o nível atual de habilidades explicou cerca de 1,5% da variação no ritmo de desenvolvimento posterior.",
"Lifts their head": "Levanta a cabeça",
"child age, months": "idade em meses",
"Two · In order": "Dois · Em ordem",
"≈ 3 mo": "≈ 3 m", "≈ 7 mo": "≈ 7 m", "≈ 12 mo": "≈ 12 m", "≈ 13 mo": "≈ 13 m",
"Sits": "Senta", "Stands": "Fica de pé", "Walks": "Anda",
"Babbling →": "Balbucio →",
"First words": "Primeiras palavras",
"Three · Wide": "Três · Amplo",
"Learning to walk": "Aprender a andar",
"8–13 mo · a 5-month range": "8–13 m · uma faixa de 5 meses",
"Dressing and feeding themselves": "Vestir-se e comer sozinho",
"17–39 mo · a 22-month range": "17–39 m · uma faixa de 22 meses",
"42 months": "42 meses",
"8–13 mo · 5 months wide": "8–13 m · faixa de 5 meses",
"17–39 mo · 22 months wide": "17–39 m · faixa de 22 meses",
"An expected age is": "Uma idade esperada é",
"Four · Windows": "Quatro · Janelas",
"Exploring objects": "Explorar objetos",
"1–5 mo": "1–5 m", "8–13 mo": "8–13 m", "14–25 mo": "14–25 m",
"First steps": "Primeiros passos",
"Five · Unpredictable": "Cinco · Imprevisível",

"Walking": "Andar",
"your baby’s age, months": "idade do seu bebê, em meses",
"Assessment at 3 months": "Avaliação aos 3 meses",
"Assessment at 2 years": "Avaliação aos 2 anos",
"a new picture every few months": "uma foto nova a cada poucos meses",
# ---------- página 3 ----------
"Where this comes from": "De onde isso vem",
"One": "Um", "Two": "Dois", "Three": "Três", "Four": "Quatro",
"Play": "Brincadeira", "Relationships": "Vínculo", "Stress": "Estresse", "Predictability": "Previsibilidade",
"Everyday moments give you": "Os momentos do dia a dia dão a você",
"ways to help.": "maneiras de ajudar.",
"Kinedu’s data help us understand how children’s skills develop. The ideas on this page come from broader research on parenting and child development. They focus on four parts of everyday life:": "Os dados do Kinedu nos ajudam a entender como as habilidades das crianças se desenvolvem. As ideias desta página vêm de uma pesquisa mais ampla sobre criação e desenvolvimento infantil. Elas se concentram em quatro partes da vida cotidiana:",
"Follow their curiosity. Join the back-and-forth.": "Siga a curiosidade dele. Entre no vai e vem.",
"Warmth, connection, and clear limits.": "Carinho, conexão e limites claros.",
"Help them through difficult moments.": "Acompanhe nos momentos difíceis.",
"Build routines they can recognize.": "Crie rotinas que ele possa reconhecer.",
"Play starts with the back-and-forth": "A brincadeira começa com o vai e vem",
"between you.": "entre vocês.",
"Your baby makes a sound. You respond. They respond again. Researchers call these back-and-forth exchanges “serve and return.” Your face, voice, and attention are part of the interaction.": "Seu bebê faz um som. Você responde. Ele responde de novo. Os pesquisadores chamam essas trocas de vai e vem de “servir e devolver”. Seu rosto, sua voz e sua atenção fazem parte da interação.",
"smile or talk back": "sorri ou fala com ele",
"responds": "responde",
"As your child grows, your role in play changes. Sometimes they lead. Sometimes you offer a prompt, introduce a rule, or show them how something works.": "Conforme o seu filho cresce, o seu papel na brincadeira muda. Às vezes ele conduz. Às vezes você sugere algo, introduz uma regra ou mostra como algo funciona.",
"Your child chooses what to explore and how to use it. There’s room to invent, experiment, and follow their curiosity.": "Seu filho escolhe o que explorar e como usar. Há espaço para inventar, experimentar e seguir a própria curiosidade.",
"You create an opportunity or offer a prompt, while your child leads the exploration. With colored cups, for example, you might invite them to sort or compare.": "Você cria uma oportunidade ou sugere algo, e o seu filho conduz a exploração. Com copos coloridos, por exemplo, você pode convidá-lo a separar ou comparar.",
"Simple games give children practice taking turns, following rules, and trying again.": "Jogos simples dão às crianças prática em esperar a vez, seguir regras e tentar de novo.",
"You show your child how to do a specific task, then give them a chance to try.": "Você mostra ao seu filho como fazer uma tarefa específica e depois dá a ele a chance de tentar.",
"Daily activity ideas": "Ideias de atividades diárias",
"Harvard’s Center on the Developing Child describes three types of stress response: positive, tolerable, and toxic. The intensity, duration, and support available to a child matter.": "O Center on the Developing Child de Harvard descreve três tipos de resposta ao estresse: positiva, tolerável e tóxica. A intensidade, a duração e o apoio disponível para a criança fazem diferença.",
"A brief challenge, with support from a caring adult, followed by a return to calm.": "Um desafio breve, com o apoio de um adulto que cuida, seguido de um retorno à calma.",
"A more serious difficulty. Supportive relationships help the child cope and recover.": "Uma dificuldade mais séria. Relações de apoio ajudam a criança a lidar com ela e se recuperar.",
"Prolonged or excessive stress without adequate adult support. This can affect development and long-term health.": "Estresse prolongado ou excessivo sem o apoio adequado de um adulto. Isso pode afetar o desenvolvimento e a saúde a longo prazo.",
"One · Play": "Um · Brincadeira",
"Your baby": "Seu bebê",
"coos": "balbucia",
"You": "Você",
"…and so on, back and forth": "…e assim, de novo e de novo",
"They lead": "Seu bebê lidera",
"You guide": "Você guia",
"Your baby leads": "Seu bebê conduz",
"You set it up, they run it": "Você prepara, o bebê conduz",
"Rules, with room to play": "Regras, mas com espaço",
"You lead": "Você dirige",
"Free play": "Brincadeira livre",
"Guided play": "Brincadeira guiada",
"Games": "Jogos",
"Direct instruction": "Instrução direta",
"Two · Relationships": "Dois · Vínculo",
"Warmth and clear limits": "Carinho e limites claros",
"can go together.": "podem andar juntos.",
"You can say no with care.": "Você pode dizer não com carinho.",
"Your child can feel upset about a limit and still receive your comfort and support.": "Seu filho pode ficar chateado com um limite e ainda assim receber o seu conforto e apoio.",
"Keep the limit. Stay connected.": "Mantenha o limite. Mantenha a conexão.",
"Name the feeling and repeat the boundary in simple words.": "Dê nome ao que ele sente e repita o limite com palavras simples.",
"Help them find their calm.": "Ajude a encontrar a calma.",
"Offer a calm voice and support while they learn to handle strong feelings.": "Ofereça uma voz tranquila e apoio enquanto ele aprende a lidar com emoções intensas.",
"You won’t get every moment right. You can reconnect and try again.": "Você não vai acertar em todos os momentos. Sempre dá para se reconectar e tentar de novo.",
"Your support can help your child": "O seu apoio pode ajudar o seu filho",
"through difficult moments.": "a atravessar os momentos difíceis.",
"Three · Stress": "Três · Estresse",
"Not all stress is": "Nem todo estresse",
"the same.": "é igual.",
"Positive": "Positivo",
"Tolerable": "Tolerável",
"Toxic": "Tóxico",
"Connect. Guide. Protect. Repeat.": "Conecte. Guie. Proteja. Repita.",
"Find ideas for putting these principles into practice with your child.": "Encontre ideias para colocar esses princípios em prática com o seu filho.",
"Explore Kinedu": "Explore o Kinedu",
"Four · Predictability": "Quatro · Previsibilidade",
"Familiar routines help your child know": "Rotinas conhecidas ajudam o seu filho a saber",
"what comes next.": "o que vem depois.",
"When our team asked Phil Fisher, of the Stanford Center on Early Childhood, what advice he would give parents, he emphasized predictability: familiar routines children can count on.": "Quando nossa equipe perguntou a Phil Fisher, do Stanford Center on Early Childhood, que conselho daria aos pais, ele destacou a previsibilidade: rotinas conhecidas com as quais as crianças podem contar.",
"Familiar patterns around meals, play, and bedtime can make the day easier to recognize. A routine can be simple and still leave room to adapt.": "Padrões conhecidos em torno das refeições, da brincadeira e da hora de dormir tornam o dia mais fácil de reconhecer. Uma rotina pode ser simples e ainda deixar espaço para se adaptar.",
"A familiar rhythm, day after day": "Um ritmo conhecido, dia após dia",
"Keep it simple, familiar,": "Que seja simples, conhecida",
"and flexible.": "e flexível.",
"Wake up": "Acordar", "Meals": "Refeições", "Play": "Brincar", "Nap": "Soneca", "Bath": "Banho", "Bedtime": "Dormir",
}

def to_pt(html, path): return localize(html, path, 'pt', META, H1, T)
